"""The words of the 40 authored cases: id -> (title, client, intro, ending). The structure (house, truth, sheet, rooms, features) lives in
specs.py and design.py; build_cases.py puts the two together into the chapter files."""

TEXTS = {
    # ---- chapter 1: First Visits ----
    "1-1": ("The Quiet Cottage", "Mrs Oake, who has lived here sixty years",
            "Mrs Oake says the parlour feels looked after, which is odd, since she lives alone. Her tea goes cold quicker than it should. She would like to know who is keeping her company.",
            "It was the housekeeper who kept the fire in for the old owners, and she only wants to be sure the hearth is swept. Mrs Oake sweeps it twice a day now, and the parlour has never been so warm."),
    "1-2": ("The Lodge by the Gate", "Mr Anand, the new gatekeeper",
            "Mr Anand keeps finding his letters answered. Neatly, in handwriting that is not his, on the days the post comes.",
            "A letter-writer who kept the estate's post stayed on in the den, still being helpful. Mr Anand leaves a pad on the desk each evening, and the replies are polite, brief and very good."),
    "1-3": ("The Bungalow on Marsh Road", "Dee, who moved in last week",
            "Dee's mugs keep ending up on the other shelf, and the back bedroom is always a little breezy. She would like the breeze to introduce itself.",
            "A small, shy presence that loved an open window had only moved what stood in the way of the breeze. Dee props the sash open an inch, and the mugs stay where she puts them."),
    "1-4": ("The Flat Over the Chemist", "Mr Voss, a night-shift baker",
            "Mr Voss sees small lights in his photographs of the parlour and the pantry. They are in no other room, and they are very polite about it.",
            "A lamp-lighter who walked the building at dusk was still making his rounds. The lights follow Mr Voss because he never could leave anyone in the dark. Mr Voss leaves a lamp on in the hall, and the rounds are shorter."),
    "1-5": ("The Terrace at Number Nine", "The Ibsen family",
            "Their daughter says the nursery has a reading lamp nobody lit. Candle wax on the sill, she adds, but no candle.",
            "A reader who spent forty winters in one chair by one candle was glad of the company. The Ibsens put a proper lamp by the chair, and their daughter reads aloud to it, a chapter a night."),
    "1-6": ("The Old Schoolhouse", "Ms Okafor, for the village hall committee",
            "The committee is turning the schoolhouse into a hall. The classroom has prints in the chalk dust on mornings after the heating was off, and the boiler room ticks at night.",
            "A night caretaker who paced the corridors to settle the building's creaks was pacing them still. The committee mended the loose board and left a stool in the corridor. The pacing stopped on a Tuesday, because there was finally somewhere to sit."),
    "1-7": ("The Farm at Three Elms", "The Marlow sisters",
            "The sisters' wool turns up in the dairy and the attic wound into neat balls, one end always pointing at whoever is nearest.",
            "A knitter who handed everyone the end of the thread had gone years without anyone to hand it to. The sisters took it in turns, and the Marlows now have more scarves than they have necks."),
    "1-8": ("The Vicarage on the Hill", "The Reverend Alder",
            "From the cellar to the bedroom, someone is tucking in the beds, folding the blankets and leaving every window open a crack. The Reverend suspects a draught with excellent manners.",
            "A nurse who tucked in every bed in every room was still doing her rounds. The Reverend thanks her at the cellar door each night, and leaves one window open a crack, for air."),
    # ---- chapter 2: Misleading Readings ----
    "2-1": ("The Draught on Ash Street", "Mrs Kamara",
            "A bedroom that is cold in August, and a kitchen where pale lights hang in the photographs. Mrs Kamara has already blamed the window. The window is, in fairness, quite draughty.",
            "The bedroom was cold because of the window, as Mrs Kamara said, and the lights were a shy lodger drawn to every lit window in the house. She apologises to the window and leaves the kitchen light on."),
    "2-2": ("The Corner Shop", "Mr Haldane",
            "The shelves are put in order overnight, and the stock is always one shelf out. The storeroom wiring hums and the shop floor is damp, so Mr Haldane has stopped trusting his instruments.",
            "A shopkeeper who kept the books in perfect order and the stock always one shelf out had never stopped working. Mr Haldane lets him move one tin a night. Takings are up."),
    "2-3": ("The Cloakroom Hooks", "Ms Rivera, head teacher",
            "Names are traced in the dust, and something follows the caretaker down the corridor and then hides behind the coats. The old window leaks cold air and the floor is damp enough to spoil any footprint.",
            "The child who loved hide and seek wanted to be found. Ms Rivera counts to twenty at the cloakroom door every Friday, loudly, and finds a very pleased coat."),
    "2-4": ("The Back Parlour", "Mr and Mrs Teague",
            "There is one lovely window, one writing desk and, each morning, a pile of thread and buttons moved to the window. The desk is full of someone else's old notes, which is not helping.",
            "A seamstress who loved one room for its light moved her thread to the good window. The Teagues put a sewing chair there, and the buttons are sorted by colour by morning."),
    "2-5": ("The Villa's Spare Room", "Dr Lindqvist",
            "The bedroom wiring hums and the bathroom floor is always damp, so Dr Lindqvist cannot tell which odd readings are the house and which are the guest.",
            "A shy little presence moved small things to make room for the breeze. Dr Lindqvist now opens the bathroom window, and finds the soap where it should be."),
    "2-6": ("The Manor Nursery", "Lady Ferrers",
            "Glow paint on the nursery walls, a street lamp that looks straight in at the landing, and pale lights in every photograph. Lady Ferrers says a spirit that wanted to be noticed would at least be unambiguous.",
            "A lamp-lighter who walked the whole house each evening only wanted the rooms bright. Lady Ferrers had the landing light turned up a notch, and the photographs went plain again."),
    "2-7": ("The Coaching Inn", "The Pell family",
            "Room two has a writing desk covered in the last guest's notes, and the beer cellar is as damp as a well. Letters are being answered in the hall, and the Pells would like to know by whom.",
            "The inn's old clerk had answered every letter ever left on the mat and could not stop tidying the post. The Pells leave him one letter a night, and he is delighted."),
    "2-8": ("The Vicarage Study", "The Reverend Moore",
            "Wiring in the study, a street lamp at the dining room window and glow paint in the cellar, which turns out to be just paint. Things move. Something follows the Reverend about. He suspects a very long thread.",
            "A knitter was handing out the end of her thread to everyone she met. The Reverend takes it, politely, and wears the result."),
    # ---- chapter 3: Two Presences ----
    "3-1": ("The Vicarage, Twice", "The Reverend Alder, again",
            "The Reverend is back, and this time there are two of them: one in the cellar keeps things in order, and one in the bedroom moves them. Two presences, one in each of two rooms. Name both.",
            "The one in the cellar tends the boiler out of habit, and the one upstairs only wants the window open. They have never met, which both of them seem to prefer."),
    "3-2": ("The Corner Shop, Again", "Mr Haldane",
            "Mr Haldane has two now: one in the store follows him about, and one in the flat above hides whenever he comes in. Two presences, one in each of two rooms. Name both.",
            "The one in the store was only helping with the invoices, and the one upstairs wanted a lit page to read by. Mr Haldane gave each of them a lamp, and the shop is the better for it."),
    "3-3": ("The Villa Library and Bedroom", "Dr Lindqvist",
            "Dr Lindqvist's library has a thread running through it and the bedroom has the linen counted twice. Two presences, one in each of two rooms. The old writing desk and the wiring do not help.",
            "The thread was a knitter's, passed hand to hand, and the linen was a shopkeeper's, counted twice for love. Dr Lindqvist took the thread and left the count."),
    "3-4": ("The Manor Pair", "Lady Ferrers",
            "The nursery has a game of hide and seek that nobody started, and the study has buttons moved to the window. Two presences, one in each of two rooms. The nursery window is very draughty.",
            "One was a child who wanted to be found, and one was a seamstress who wanted the good light. Lady Ferrers found the first and moved her chair to the second."),
    "3-5": ("The Inn's Two Guests", "The Pell family",
            "A taproom where the stools are squared to the bar every night, and Room one where letters are answered and something follows the maid. Two presences, one in each of two rooms. Wiring in the taproom, a street lamp in Room one.",
            "The taproom's was the old landlord's fire-minder, and Room one's was the inn's helpful clerk. The Pells set a log on the fire and a pen on the desk."),
    "3-6": ("The Farmhouse and the Attic", "The Marlow sisters",
            "The dairy shifts small things and avoids everyone. The attic follows you up the stairs and hands you wool. Two presences, one in each of two rooms. The dairy floor is permanently wet.",
            "A shy one that moves things for the breeze, and a knitter handing out thread. The sisters leave the dairy window ajar, and take the end of the wool in the attic."),
    "3-7": ("Number Nine, Both Floors", "The Ibsen family",
            "The kitchen has a shy someone who reads by one candle. The nursery has a child following everyone about. Two presences, one in each of two rooms. The nursery window leaks cold.",
            "A reader by one candle, and a child who wanted to be found. The Ibsens' daughter reads to one and plays with the other, in that order, every night."),
    "3-8": ("The Mill, Top and Bottom", "Mr Acheson",
            "The workshop moves things and counts them. The loft moves things and sews them. Two presences, one in each of two rooms. The workshop wall glows with old paint and the loft desk is covered in notes.",
            "A mill clerk who kept the books and a seamstress who loved one window, both moving small things. Mr Acheson set a ledger on the workshop bench and a chair in the loft, and they stopped moving things at once."),
    # ---- chapter 4: Keepsakes ----
    "4-1": ("The Hand Mirror", "Ms Thorne, an estate agent",
            "Ms Thorne cannot sell the villa. Pale lights drift through the conservatory and bedroom, and a silver hand mirror sits on the dresser that nobody admits to owning. Its room will throw off any reading.",
            "The lights were a lamp-lighter making his rounds, and the mirror was how he checked each room was bright. Ms Thorne returned it to the dresser. The villa sold to a family who love lamps."),
    "4-2": ("The Music Box", "Mr Brandt",
            "A small brass music box turns up in a different place every morning, and a thread of wool follows it. The nursery room it keeps returning to will fool any reading.",
            "A knitter who kept her music box for company was following the family about with the end of her thread. Mr Brandt winds the box on Sundays, and the wool has stopped wandering."),
    "4-3": ("The Thimble in Room One", "Nell Fairweather, the inn's new landlady",
            "Beds made at every hour, windows left open a crack, and a dented silver thimble in Room one that will not stay in a drawer. The thimble's room swamps every instrument.",
            "A nurse who tucked in every bed still carried her thimble for the buttons. Nell sewed one onto a pillow, and the beds have been left alone since."),
    "4-4": ("The Brass Key", "The Castellano brothers",
            "Footsteps in the workshop and the store, and a worn brass key that migrates from nail to nail. The workshop where it hangs will not give a clean reading.",
            "A night worker who walked the floors to settle the building carried the key as proof that every door was locked. The brothers hung it by the main door, and the footsteps stopped there."),
    "4-5": ("The Paperweight", "Mrs Duval",
            "The study is tidy past all reason, a glass paperweight is squared to the edge of the desk, and the bedroom has a desk full of someone else's notes. The study will not give a clean reading.",
            "A letter-writer who answered every note was keeping the pile in order with her paperweight. Mrs Duval set it on her own letters, and the replies are now both neat and kind."),
    "4-6": ("The Teacup", "Mr Osei",
            "A chipped blue teacup sits in the flat above the shop, tucked well back, and the street lamp makes the shop floor useless for readings. Something slips away whenever Mr Osei walks in.",
            "A lodger drawn to every lit window liked the teacup because it caught the lamplight. Mr Osei moves it to the front window each evening, and the lodger no longer hides."),
    "4-7": ("The Button Tin", "The Whitlock cousins",
            "An old biscuit tin of buttons has been pushed to the back of the dairy shelf, as if it prefers not to be seen. The kitchen draught is dreadful. The dairy tin will fool every instrument.",
            "A shy presence that loved an open window kept its buttons in the tin, out of the way. The cousins put it by the open window, and it keeps itself company."),
    "4-8": ("The Wool Basket", "The new manager of the Hotel Marrow",
            "A basket of grey wool follows guests down the corridor of the first floor, always facing the door. The gallery wall paint glows without being asked. The suite where the basket stays will confuse every reading.",
            "A child who loved hide and seek used the wool basket to follow people and hide behind. The manager plays one game a week, and the basket stays in the suite."),
    # ---- chapter 5: The Big Houses ----
    "5-1": ("The Old Mill", "The Mill Trust",
            "The Mill Trust opens in spring. The mill floor, the workshop and the loft all show signs. The hall wiring hums, the loft has a desk of old notes, and the boiler room is draughty.",
            "A shopkeeper turned mill clerk, tidy and quietly moving the stock one shelf over, had the whole building in his keeping. The Trust framed a ledger page in the workshop, and he moves nothing now but the light."),
    "5-2": ("The Abbey House", "The Heritage Committee",
            "A chapel with a street lamp in its window, a bell loft with paint that glows, a damp cellar, and a scriptorium that is wilfully quiet. Lights follow visitors in the three rooms that matter.",
            "A lamp-lighter who walked the whole abbey at dusk was following the committee because he never could leave anyone in the dark. They left a lantern in each of the three rooms, and he took the rounds off."),
    "5-3": ("The Seaside Hotel", "The Hotel Marrow",
            "The ballroom has a draught that comes from nowhere, the suite has wiring that hums, and two presences are in two rooms. One keeps its room tidy. One follows guests about. Name both.",
            "The ballroom's was the hotel's fire-minder, and the suite's a knitter who followed guests to hand them the end of her wool. The staff say good evening to both, and the guests say the hotel is lovely."),
    "5-4": ("The Little Theatre", "The Little Theatre Company",
            "Footsteps in the ballroom, the loft and the gallery. Beds in the dress circle are made. A street lamp shines on the stage. A music box sits in the loft, and its room will fool every instrument.",
            "A nurse who walked the whole theatre to tuck up the cast had left the music box as a lullaby for the loft. The Company wound it on opening night, and the performances run a little quieter."),
    "5-5": ("The Country Estate", "The Estate Trustees",
            "The music room wiring hums, the nursery floor is damp, and the attic is draughty and holds a teacup that will not give a clean reading. Small things move and slip away.",
            "A shy presence that loved an open window had been keeping the teacup warm. The trustees leave the attic window ajar, and the music room is only a music room."),
    "5-6": ("The Grand House", "The Grand House Society",
            "Two presences: one in the music room on the first floor, one in the chapel on the ground floor. The music room desk and the chapel floor throw off two of the readings. Name both.",
            "A seamstress who loved the light in the music room and a child who loved to be found in the chapel. The Society moved a chair to the first and counts to twenty for the second."),
    "5-7": ("The Estate, Four Rooms", "The Estate Trustees, a second visit",
            "Footsteps in four rooms of the estate: the library, the kitchen, the study and the scullery. Wiring in the kitchen, a desk in the library and glow paint in the study make some readings useless.",
            "The night worker who paced the floors had finally got around the whole estate. The Trustees set a stool in each of the four rooms, and he sits on one of them."),
    "5-8": ("The Last House", "The Society, again, with everything",
            "The Grand House is the biggest on the books. A street lamp in the gallery, a desk in the library, glow paint in the attic, a hand mirror in the attic that fools every reading, and a letter-writer following everyone about.",
            "A letter-writer who answered every note had been tidying the letters of a house with no one left to write them. The Society left a pad on the desk, and by morning there was a reply in clean handwriting: thank you, the house is in order."),
}
