/*
 * Hub "Download for offline" (TODO Y-9). Loaded on index.html (per-card buttons) and settings.html
 * (the manager list). No service-worker change: the page uses the Cache Storage API itself.
 *
 * How it lines up with sw.js (read this before changing either file):
 *  - sw.js keeps ONE live cache named "site-cache-v<SW_VERSION>" and its fetch handler reads only
 *    that cache (caches.open(CACHE_NAME) then cache.match(request)). So this file finds the live
 *    cache (the highest site-cache-v<N>) and adds the game's files to it under their absolute URLs.
 *    The worker's offline fallback then finds them like anything it cached itself.
 *  - sw.js's activate step deletes every cache that is not the current one. A deploy that bumps
 *    SW_VERSION therefore wipes these downloads. The page notices (a recorded download whose files
 *    are no longer all cached shows "Needs downloading again") and never pretends otherwise.
 *    Keeping them across versions needs a small sw.js change, see planning notes in the report.
 *  - Files sw.js precaches anyway are marked "precached" in offline-manifest.json and are never
 *    removed by "Remove". The Python runtime (Pyodide) is shared by every game and is only removed
 *    when no other game is available offline.
 *
 * offline-manifest.json is generated by scripts/generate-offline-manifest.py (file lists, sizes).
 * Sizes shown are honest: bytes still missing from the cache for the estimate, storage readout
 * from navigator.storage.estimate(). Every state is plain text. Nothing here ever touches the
 * backend.
 *
 * window.HubOffline: supported(), loadManifest(), formatBytes(n), status(slug), download(slug,
 * { onProgress, signal }), remove(slug), estimate(), recorded(), mountSettings(container).
 */
(function () {
  "use strict";

  const STORE_KEY = "hub_offline_games";
  const MANIFEST_URL = "offline-manifest.json";
  const LIVE_CACHE_RE = /^site-cache-v(\d+)$/;
  const CONCURRENCY = 4;
  const SPACE_MARGIN = 1.15; // ask for a little more room than the files need

  let manifestPromise = null;

  function lsGet(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
  function lsSet(k, v) { try { localStorage.setItem(k, v); } catch (e) { /* convenience only */ } }

  function supported() {
    return typeof caches !== "undefined" && typeof caches.open === "function" && typeof fetch === "function";
  }

  function formatBytes(n) {
    if (typeof n !== "number" || !isFinite(n) || n < 0) return "unknown size";
    if (n < 1024) return n + " B";
    if (n < 1024 * 1024) return (n / 1024).toFixed(n < 10240 ? 1 : 0) + " KB";
    if (n < 1024 * 1024 * 1024) return (n / (1024 * 1024)).toFixed(n < 10 * 1024 * 1024 ? 1 : 0) + " MB";
    return (n / (1024 * 1024 * 1024)).toFixed(1) + " GB";
  }

  function loadManifest() {
    if (!manifestPromise) {
      manifestPromise = fetch(MANIFEST_URL)
        .then((res) => (res.ok ? res.json() : null))
        .then((data) => (data && data.games && typeof data.games === "object" ? data : null))
        .catch(() => null);
    }
    return manifestPromise;
  }

  // ---- what was downloaded here (a record, not proof: proof is the cache itself) ----------------

  function recorded() {
    try {
      const raw = JSON.parse(lsGet(STORE_KEY) || "{}");
      const out = {};
      if (raw && typeof raw === "object") {
        Object.keys(raw).forEach((slug) => {
          const r = raw[slug];
          if (/^[a-z0-9-]{1,40}$/.test(slug) && r && typeof r === "object") {
            out[slug] = { at: typeof r.at === "string" ? r.at.slice(0, 40) : "", bytes: Number.isFinite(r.bytes) ? r.bytes : null };
          }
        });
      }
      return out;
    } catch (e) { return {}; }
  }
  function writeRecord(map) { lsSet(STORE_KEY, JSON.stringify(map)); }

  // ---- manifest entries -> absolute urls --------------------------------------------------------

  function entriesOf(game) {
    const list = [];
    (game.files || []).forEach((e) => list.push({ url: new URL(e.path, document.baseURI).href, bytes: e.bytes, precached: !!e.precached, external: false, kind: "file" }));
    (game.shared || []).forEach((e) => list.push({ url: new URL(e.path, document.baseURI).href, bytes: e.bytes, precached: !!e.precached, external: false, kind: "shared" }));
    (game.cdn || []).forEach((e) => list.push({ url: e.url, bytes: typeof e.bytes === "number" ? e.bytes : null, precached: false, external: true, kind: e.kind || "cdn" }));
    return list;
  }

  async function liveCacheName() {
    const names = await caches.keys();
    let best = null;
    names.forEach((n) => {
      const m = LIVE_CACHE_RE.exec(n);
      if (m && (!best || Number(m[1]) > best.v)) best = { name: n, v: Number(m[1]) };
    });
    return best ? best.name : null;
  }

  async function isCached(url) {
    try { return Boolean(await caches.match(url)); } catch (e) { return false; }
  }

  async function cachedFlags(entries) {
    const flags = new Array(entries.length).fill(false);
    let next = 0;
    async function worker() {
      while (next < entries.length) {
        const i = next++;
        flags[i] = await isCached(entries[i].url);
      }
    }
    await Promise.all([worker(), worker(), worker(), worker()]);
    return flags;
  }

  /**
   * { state, totalBytes, missingBytes, missingCount, missingUnknown, storedBytes, at }
   * state: "unsupported" | "none" (nothing or only part stored, never downloaded) | "ready" |
   *        "stale" (downloaded earlier, files since removed, e.g. by a service-worker update).
   * missingBytes counts only the files still to fetch; missingUnknown is true when a missing
   * file has no known size. storedBytes is the size of cached files the app would not keep anyway.
   */
  async function status(slug) {
    const manifest = await loadManifest();
    const game = manifest && manifest.games[slug];
    if (!game) return { state: "unsupported" };
    if (!supported()) return { state: "unsupported" };
    const entries = entriesOf(game);
    const flags = await cachedFlags(entries);
    let missingBytes = 0; let missingCount = 0; let missingUnknown = false; let storedBytes = 0; let totalBytes = 0;
    entries.forEach((e, i) => {
      totalBytes += e.bytes || 0;
      if (flags[i]) { if (!e.precached) storedBytes += e.bytes || 0; return; }
      missingCount += 1;
      if (typeof e.bytes === "number") missingBytes += e.bytes; else missingUnknown = true;
    });
    const rec = recorded()[slug];
    const complete = missingCount === 0;
    let state = "none";
    if (complete) state = "ready";
    else if (rec) state = "stale";
    return { state, totalBytes, missingBytes, missingCount, missingUnknown, storedBytes, at: rec ? rec.at : "", fromPlay: complete && !rec };
  }

  async function estimate() {
    try {
      if (navigator.storage && navigator.storage.estimate) {
        const e = await navigator.storage.estimate();
        return { usage: e.usage, quota: e.quota };
      }
    } catch (err) { /* below */ }
    return null;
  }

  // ---- download ---------------------------------------------------------------------------------

  async function fetchIntoCache(cache, entry, onBytes, signal) {
    const opts = entry.external ? { signal } : { cache: "reload", signal };
    let res;
    try {
      res = await fetch(entry.url, opts);
    } catch (err) {
      if (signal && signal.aborted) throw err;
      if (!entry.external) throw err;
      // A CDN that refuses CORS can still be stored as an opaque response, which is all a <script>
      // or the runtime loader needs. Its size is then taken from the manifest.
      res = await fetch(entry.url, { mode: "no-cors", signal });
      await cache.put(entry.url, res);
      onBytes(entry.bytes || 0);
      return;
    }
    if (!res.ok) throw new Error("HTTP " + res.status);
    if (!res.body || !res.body.getReader) {
      const blob = await res.clone().blob();
      await cache.put(entry.url, res);
      onBytes(blob.size);
      return;
    }
    const counter = res.clone().body.getReader();
    const counting = (async () => {
      for (;;) {
        const part = await counter.read();
        if (part.done) return;
        onBytes(part.value.length);
      }
    })();
    await Promise.all([cache.put(entry.url, res), counting]);
  }

  function describeFailure(failed) {
    const first = failed[0];
    const name = first.url.split("/").pop().split("?")[0] || first.url;
    return failed.length === 1
      ? "Could not download " + name + " (" + first.reason + ")."
      : "Could not download " + failed.length + " files, the first was " + name + " (" + first.reason + ").";
  }

  /**
   * Resolves { ok, message, failed:[{url,reason}], bytes }. Never throws. Files already cached on
   * this device that are immutable (the CDN runtime) are skipped; the game's own files are always
   * fetched fresh so an old copy is never kept by mistake.
   */
  async function download(slug, options) {
    const opts = options || {};
    const report = typeof opts.onProgress === "function" ? opts.onProgress : () => {};
    const manifest = await loadManifest();
    const game = manifest && manifest.games[slug];
    if (!game || !supported()) return { ok: false, failed: [], message: "Offline downloads are not available in this browser.", bytes: 0 };
    if (typeof navigator !== "undefined" && navigator.onLine === false) {
      return { ok: false, failed: [], message: "You are offline. Connect to the internet to download this game.", bytes: 0 };
    }
    const liveName = await liveCacheName();
    if (!liveName) {
      return { ok: false, failed: [], message: "The offline cache is not ready yet. The app's service worker installs after your first visit: reload this page once, then try again.", bytes: 0 };
    }
    const all = entriesOf(game);
    const flags = await cachedFlags(all);
    const todo = all.filter((e, i) => !(e.external && flags[i]));
    const expected = todo.reduce((sum, e) => sum + (e.bytes || 0), 0);
    const est = await estimate();
    if (est && typeof est.quota === "number" && typeof est.usage === "number" && est.quota - est.usage < expected * SPACE_MARGIN) {
      return {
        ok: false, failed: [], bytes: 0,
        message: "Not enough free storage on this device: this download needs about " + formatBytes(expected) + " and about " + formatBytes(Math.max(0, est.quota - est.usage)) + " is free.",
      };
    }
    const cache = await caches.open(liveName);
    const failed = [];
    let loaded = 0; let done = 0; let next = 0;
    const signal = opts.signal;
    report({ loaded, expected, done, count: todo.length });
    async function worker() {
      while (next < todo.length && !(signal && signal.aborted)) {
        const entry = todo[next++];
        try {
          await fetchIntoCache(cache, entry, (n) => { loaded += n; report({ loaded, expected, done, count: todo.length }); }, signal);
        } catch (err) {
          if (signal && signal.aborted) return;
          failed.push({ url: entry.url, reason: err && err.message ? err.message : "network error" });
        }
        done += 1;
        report({ loaded, expected, done, count: todo.length });
      }
    }
    const workers = [];
    for (let i = 0; i < Math.min(CONCURRENCY, todo.length); i += 1) workers.push(worker());
    await Promise.all(workers);
    if (signal && signal.aborted) return { ok: false, cancelled: true, failed, bytes: loaded, message: "Download cancelled. Nothing was marked as available offline." };
    if (failed.length) {
      return { ok: false, failed, bytes: loaded, message: describeFailure(failed) + " The game is not marked as available offline. Check your connection and try again." };
    }
    const map = recorded();
    map[slug] = { at: new Date().toISOString(), bytes: all.reduce((s, e) => s + (e.bytes || 0), 0) };
    writeRecord(map);
    return { ok: true, failed: [], bytes: loaded, message: "Available offline." };
  }

  // ---- remove -----------------------------------------------------------------------------------

  async function remove(slug) {
    const manifest = await loadManifest();
    const game = manifest && manifest.games[slug];
    if (!game || !supported()) return { removed: 0, bytes: 0 };
    // Anything another offline-ready game needs, or sw.js keeps anyway, stays.
    const keep = new Set();
    const slugs = Object.keys(manifest.games).filter((s) => s !== slug);
    for (const other of slugs) {
      const st = await status(other);
      if (st.state === "ready") entriesOf(manifest.games[other]).forEach((e) => keep.add(e.url));
    }
    const names = (await caches.keys()).filter((n) => LIVE_CACHE_RE.test(n));
    let removed = 0; let bytes = 0;
    for (const e of entriesOf(game)) {
      if (e.precached || keep.has(e.url)) continue;
      for (const name of names) {
        const cache = await caches.open(name);
        if (await cache.delete(e.url)) { removed += 1; bytes += e.bytes || 0; }
      }
    }
    const map = recorded();
    delete map[slug];
    writeRecord(map);
    return { removed, bytes };
  }

  // ---- text -------------------------------------------------------------------------------------

  function dateText(iso) {
    const d = new Date(iso);
    return isNaN(d.getTime()) ? "" : d.toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" });
  }

  function sizePhrase(st) {
    const size = formatBytes(st.missingBytes);
    return st.missingUnknown ? "about " + size + " plus files of unknown size" : "about " + size;
  }

  function readyText(st) {
    if (st.fromPlay) return "Available offline: everything this game needs is already stored on this device from playing it.";
    const when = st.at ? " (downloaded " + dateText(st.at) + ")" : "";
    return "Available offline" + when + ". " + (st.storedBytes ? "Takes " + formatBytes(st.storedBytes) + " of extra storage." : "");
  }

  // ---- card controls (index.html) ---------------------------------------------------------------

  function cardSlug(card) {
    const w = card.querySelector(".review-widget");
    return w ? w.dataset.gameSlug : "";
  }

  function actionsHost(card) {
    let host = card.querySelector(".title-card-actions");
    if (!host) {
      host = document.createElement("div");
      host.className = "title-card-actions";
      const link = card.querySelector(".title-card-link");
      if (link) link.insertAdjacentElement("afterend", host); else card.appendChild(host);
    }
    return host;
  }

  function buildCard(card, slug, game) {
    const name = (card.querySelector(".title-card-name") || {}).textContent || slug;
    const wrap = document.createElement("div");
    wrap.className = "title-card-offline";
    const button = document.createElement("button");
    button.type = "button";
    button.className = "offline-button secondary";
    const statusId = "offline-status-" + slug;
    button.setAttribute("aria-describedby", statusId);
    const cancel = document.createElement("button");
    cancel.type = "button";
    cancel.className = "offline-cancel account-link-button";
    cancel.textContent = "Cancel";
    cancel.hidden = true;
    const progress = document.createElement("progress");
    progress.className = "offline-progress";
    progress.max = 100;
    progress.value = 0;
    progress.hidden = true;
    progress.setAttribute("aria-label", "Download progress for " + name);
    const progressText = document.createElement("span");
    progressText.className = "offline-progress-text";
    progressText.hidden = true;
    const note = document.createElement("p");
    note.className = "offline-status";
    note.id = statusId;
    note.setAttribute("role", "status");
    wrap.append(button, cancel, progress, progressText, note);
    actionsHost(card).appendChild(wrap);

    let controller = null;
    let busy = false;
    let lastState = "none";

    async function refresh(message) {
      if (busy) return;
      const st = await status(slug);
      lastState = st.state;
      if (st.state === "unsupported") { wrap.hidden = true; return; }
      wrap.hidden = false;
      const offline = navigator.onLine === false;
      if (st.state === "ready") {
        button.textContent = "Remove offline copy";
        button.disabled = false;
        button.dataset.mode = "remove";
        note.textContent = message || readyText(st);
      } else {
        button.dataset.mode = "download";
        button.textContent = st.state === "stale" ? "Download again (" + sizePhrase(st) + ")" : "Download for offline (" + sizePhrase(st) + ")";
        button.disabled = offline;
        note.textContent = message || (st.state === "stale"
          ? "Needs downloading again: an update cleared the stored copy."
          : offline ? "You are offline: connect to download this game." : "Not stored on this device. It will not open without a connection.");
      }
    }

    function announceChange() {
      window.dispatchEvent(new CustomEvent("hub-offline-change", { detail: { slug } }));
    }

    function setBusy(on) {
      busy = on;
      button.disabled = on;
      cancel.hidden = !on;
      progress.hidden = !on;
      progressText.hidden = !on;
    }

    button.addEventListener("click", async () => {
      if (busy) return;
      if (button.dataset.mode === "remove") {
        setBusy(true);
        note.textContent = "Removing the offline copy…";
        const r = await remove(slug);
        setBusy(false);
        await refresh("Offline copy removed" + (r.bytes ? " (" + formatBytes(r.bytes) + " freed)" : "") + ".");
        announceChange();
        return;
      }
      controller = typeof AbortController === "function" ? new AbortController() : null;
      setBusy(true);
      note.textContent = "Downloading " + name + "…";
      progress.removeAttribute("value");
      const result = await download(slug, {
        signal: controller ? controller.signal : undefined,
        onProgress: (p) => {
          if (p.expected > 0) {
            progress.max = p.expected;
            progress.value = Math.min(p.loaded, p.expected);
            progressText.textContent = formatBytes(p.loaded) + " of about " + formatBytes(p.expected);
          } else {
            progressText.textContent = p.done + " of " + p.count + " files";
          }
        },
      });
      setBusy(false);
      controller = null;
      await refresh(result.ok ? "" : result.message);
      announceChange();
    });
    cancel.addEventListener("click", () => { if (controller) controller.abort(); });
    window.addEventListener("hub-offline-change", (ev) => { if (!ev.detail || ev.detail.slug !== slug) refresh(); });
    window.addEventListener("online", () => refresh());
    window.addEventListener("offline", () => refresh());
    refresh();
    return { refresh, getState: () => lastState };
  }

  function lobbyLine(manifest) {
    const line = document.getElementById("offline-storage-line");
    if (!line) return () => {};
    async function update() {
      const slugs = Object.keys(manifest.games);
      const states = await Promise.all(slugs.map((s) => status(s)));
      const ready = states.filter((s) => s.state === "ready" && !s.fromPlay).length;
      const stored = states.reduce((sum, s) => sum + (s.state === "ready" ? s.storedBytes : 0), 0);
      if (!ready) { line.hidden = true; return; }
      const est = await estimate();
      line.textContent = ready + " of " + slugs.length + " games downloaded for offline use, taking " + formatBytes(stored) +
        (est && est.usage !== undefined ? " (this site uses " + formatBytes(est.usage) + " of " + formatBytes(est.quota) + " in total)" : "") + ". Manage them in Settings.";
      line.hidden = false;
    }
    return update;
  }

  async function initLobby() {
    const cards = Array.from(document.querySelectorAll(".title-card"));
    if (!cards.length || !supported()) return;
    const manifest = await loadManifest();
    if (!manifest) return;
    const updateLine = lobbyLine(manifest);
    cards.forEach((card) => {
      const slug = cardSlug(card);
      if (slug && manifest.games[slug]) buildCard(card, slug, manifest.games[slug]);
    });
    let timer = null;
    window.addEventListener("hub-offline-change", () => { clearTimeout(timer); timer = setTimeout(updateLine, 300); });
    updateLine();
  }

  // ---- settings page manager --------------------------------------------------------------------

  async function mountSettings(container) {
    if (!container) return;
    const manifest = await loadManifest();
    container.textContent = "";
    if (!supported() || !manifest) {
      const p = document.createElement("p");
      p.className = "hub-note";
      p.textContent = !supported() ? "This browser has no offline storage, so games cannot be downloaded for offline use." : "The list of downloadable files could not be loaded right now.";
      container.appendChild(p);
      return;
    }
    const total = document.createElement("p");
    total.className = "hub-note";
    total.setAttribute("role", "status");
    const list = document.createElement("ul");
    list.className = "offline-manage-list";
    container.append(total, list);
    const names = {};
    try {
      const html = await (await fetch("index.html")).text();
      const doc = new DOMParser().parseFromString(html, "text/html");
      doc.querySelectorAll(".title-card").forEach((c) => {
        const w = c.querySelector(".review-widget");
        const n = c.querySelector(".title-card-name");
        if (w && n) names[w.dataset.gameSlug] = n.textContent.trim();
      });
    } catch (e) { /* slugs are shown instead */ }

    async function render() {
      list.textContent = "";
      const slugs = Object.keys(manifest.games);
      let ready = 0; let stale = 0; let stored = 0;
      for (const slug of slugs) {
        const st = await status(slug);
        if (st.state !== "ready" && st.state !== "stale") continue;
        if (st.state === "ready") { ready += 1; stored += st.storedBytes; } else stale += 1;
        const li = document.createElement("li");
        li.className = "offline-manage-item";
        const label = document.createElement("span");
        label.textContent = (names[slug] || slug) + ": " + (st.state === "ready" ? (st.fromPlay ? "stored from playing" : "downloaded") + ", " + formatBytes(st.storedBytes) + " extra" : "needs downloading again");
        const btn = document.createElement("button");
        btn.type = "button";
        btn.className = "secondary";
        btn.textContent = st.state === "ready" ? "Remove" : "Forget";
        btn.setAttribute("aria-label", (st.state === "ready" ? "Remove the offline copy of " : "Forget the download record of ") + (names[slug] || slug));
        btn.addEventListener("click", async () => {
          btn.disabled = true;
          const r = await remove(slug);
          await render();
          window.dispatchEvent(new CustomEvent("hub-offline-change", { detail: { slug } }));
          total.textContent = "Removed " + (names[slug] || slug) + (r.bytes ? " (" + formatBytes(r.bytes) + " freed). " : ". ") + total.textContent;
        });
        li.append(label, btn);
        list.appendChild(li);
      }
      const est = await estimate();
      const use = est && est.usage !== undefined ? " This site uses " + formatBytes(est.usage) + " of " + formatBytes(est.quota) + " available on this device in total." : "";
      const staleNote = stale ? " " + stale + " needs downloading again (an update cleared the stored files)." : "";
      total.textContent = ready
        ? ready + (ready === 1 ? " game is" : " games are") + " stored for offline use, taking " + formatBytes(stored) + " of extra space." + staleNote + use
        : "No games are stored for offline use." + staleNote + use + " Open the hub, choose Show details on a game and press Download for offline.";
    }
    await render();
  }

  window.HubOffline = { supported, loadManifest, formatBytes, status, download, remove, estimate, recorded, mountSettings, entriesOf };

  if (document.getElementById("game-grid")) {
    if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", initLobby);
    else initLobby();
  }
})();
