"""Authoring helper: for each chart print the naive plan's miss, the par plan's result and the forecast plan's result.

    python3 tools/check_charts.py [chart-id ...]
    python3 tools/check_charts.py --write      # also write pars.py from the waypoints (the par plans)
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import charts  # noqa: E402
import sim  # noqa: E402
import solver  # noqa: E402


def par_for(chart):
    legs, _end = solver.route(chart, [tuple(p) for p in chart["waypoints"]], model="true", wait=chart.get("par_wait", 0.0))
    return legs


def main(argv):
    write = "--write" in argv
    wanted = [a for a in argv if not a.startswith("--")]
    pars = {}
    for chart in charts.all_charts():
        if wanted and chart["id"] not in wanted:
            continue
        legs = par_for(chart)
        pars[chart["id"]] = legs
        res = sim.sail(chart, legs)
        sc = sim.score(chart, legs, res)
        fc_legs, _ = solver.route(chart, [tuple(p) for p in chart["waypoints"]], model="charted", wait=chart.get("par_wait", 0.0))
        fc_res = sim.sail(chart, fc_legs)
        fc = sim.score(chart, fc_legs, fc_res)
        print("%-10s naive miss %5.1f (fails=%s)  par: %d legs %4.1f h/%g stars %d miss %.2f aground=%s close=%s | forecast: miss %.2f stars %d aground=%s | route %.1f nm"
              % (chart["id"], sc["naive_miss_nm"], chart["naive_fails"], len(legs), sim.plan_hours(legs), chart["deadline"], sc["stars"], sc["miss_nm"],
                 (res["aground"] or {}).get("name"), res["close"], fc["miss_nm"], fc["stars"], bool(fc_res["aground"]), sim.plan_distance(legs)))
        if "--legs" in argv:
            for leg in legs:
                print("     ", leg)
    if write:
        lines = ['"""Dead Reckoning -- the par plans: the authored solution to every chart, one list of legs each.',
                 '',
                 'GENERATED by tools/check_charts.py --write from each chart\'s `waypoints`; do not edit by hand. tests/test_charts.py',
                 'checks that every par plan still lands three stars on its chart."""',
                 '', 'PARS = {']
        for cid, legs in pars.items():
            lines.append('    "%s": [' % cid)
            for leg in legs:
                lines.append('        {"heading": %d, "speed": %g, "hours": %g},' % (leg["heading"], leg["speed"], leg["hours"]))
            lines.append('    ],')
        lines.append('}')
        Path(__file__).resolve().parent.parent.joinpath("pars.py").write_text("\n".join(lines) + "\n", encoding="utf-8")
        print("wrote pars.py with %d plans" % len(pars))


if __name__ == "__main__":
    main(sys.argv[1:])
