"""Logic Gates -- chapters 1 and 2 (levels 1-17), combinational. See levels.py for the fields.

Inputs are listed most significant first and the truth table rows count up in that order. `fn` gets {input: bit} and returns
{output: bit}; it is the spec, written independently of the reference solution `ref`."""


def num(v, prefix, bits):
    """The number on wires prefix{bits-1} ... prefix0."""
    return sum(v[f"{prefix}{i}"] << i for i in range(bits))


CH1 = [
    {"id": "straight-through", "name": "Straight Through", "ins": ["A"], "outs": ["Y"],
     "goal": "Make lamp Y follow switch A.",
     "fn": lambda v: {"Y": v["A"]},
     "ref": "Y := A", "unlock": "not",
     "nudge": "A wire can run straight from a switch to a lamp. No chip is needed.",
     "hint": "Open the list for lamp Y (or tap switch A, then tap lamp Y) and choose switch A as its source.",
     "log": "Core board 1. First job: prove a bare wire still carries a signal after eleven years of dark."},
    {"id": "invert", "name": "Invert", "ins": ["A"], "outs": ["Y"],
     "goal": "Lamp Y must be on exactly when switch A is off.",
     "fn": lambda v: {"Y": 1 - v["A"]},
     "ref": "Y := not(A)", "unlock": "and",
     "nudge": "You need a chip that flips a signal.",
     "hint": "Add one NOT chip. Wire switch A into it and its output into lamp Y.",
     "log": "Core board 2. Vale's pencil note beside it: 'NOT is the only honest chip. It never agrees with you.'"},
    {"id": "both", "name": "Both", "ins": ["A", "B"], "outs": ["Y"],
     "goal": "Lamp Y lights only when both switches are on.",
     "fn": lambda v: {"Y": v["A"] & v["B"]},
     "ref": "Y := and(A, B)", "unlock": "or",
     "nudge": "One chip does exactly this.",
     "hint": "Add an AND chip: switch A into its first input, switch B into its second, its output into lamp Y.",
     "log": "Core board 3. An interlock: two keys must turn together."},
    {"id": "either", "name": "Either", "ins": ["A", "B"], "outs": ["Y"],
     "goal": "Lamp Y lights when either switch, or both, is on.",
     "fn": lambda v: {"Y": v["A"] | v["B"]},
     "ref": "Y := or(A, B)", "unlock": None,
     "nudge": "Try the chip you just earned.",
     "hint": "Add an OR chip and wire A and B into it, then its output into lamp Y.",
     "log": "Core board 4. A warning light that stays on if any one of the sensors complains."},
    {"id": "odd-one-out", "name": "Odd One Out", "ins": ["A", "B"], "outs": ["Y"],
     "goal": "Lamp Y lights when the two switches differ. XOR is not on the shelf yet: build it from NOT, AND and OR.",
     "fn": lambda v: {"Y": v["A"] ^ v["B"]},
     "ref": "a = and(A, B); n = not(a); o = or(A, B); Y := and(n, o)", "unlock": "xor",
     "nudge": "Differ means: at least one is on, but not both.",
     "hint": "OR says at least one is on. AND says both are on. Put the AND through a NOT, then AND that with the OR.",
     "log": "Core board 5. Vale wrote 'differ' in the margin and then 'who decides which one is right?' and left it there."},
    {"id": "not-both", "name": "Not Both", "ins": ["A", "B"], "outs": ["Y"],
     "goal": "Lamp Y is on unless both switches are on.",
     "fn": lambda v: {"Y": 1 - (v["A"] & v["B"])},
     "ref": "a = and(A, B); Y := not(a)", "unlock": "nand",
     "nudge": "It is the opposite of Both.",
     "hint": "AND the switches together, then send that through a NOT into lamp Y.",
     "log": "Core board 6. Two pumps may never run at the same time. Someone once forgot that."},
    {"id": "neither", "name": "Neither", "ins": ["A", "B"], "outs": ["Y"],
     "goal": "Lamp Y lights only when both switches are off.",
     "fn": lambda v: {"Y": 1 - (v["A"] | v["B"])},
     "ref": "o = or(A, B); Y := not(o)", "unlock": "nor",
     "nudge": "It is the opposite of Either.",
     "hint": "OR the switches, then send that through a NOT into lamp Y.",
     "log": "Core board 7. The 'all quiet' light. It lies less often than people do."},
    {"id": "same", "name": "Same", "ins": ["A", "B"], "outs": ["Y"],
     "goal": "Lamp Y lights when the two switches match, both on or both off.",
     "fn": lambda v: {"Y": 1 - (v["A"] ^ v["B"])},
     "ref": "x = xor(A, B); Y := not(x)", "unlock": "xnor",
     "nudge": "The chip you just earned says when they differ.",
     "hint": "Wire A and B into an XOR, then its output through a NOT into lamp Y.",
     "log": "Core board 8. A comparison board. First chapter done: the shelf is full of gates."},
]

CH2 = [
    {"id": "three-keys", "name": "Three Keys", "ins": ["A", "B", "C"], "outs": ["Y"],
     "goal": "Lamp Y lights only when all three switches are on.",
     "fn": lambda v: {"Y": v["A"] & v["B"] & v["C"]},
     "ref": "t = and(A, B); Y := and(t, C)", "unlock": "and3", "label": "AND 3",
     "nudge": "A gate takes only two inputs, but gates can feed gates.",
     "hint": "AND two of the switches, then AND that result with the third.",
     "log": "Vault door. Three keys, three hands. Vale's note: 'Always three. Never me alone.'"},
    {"id": "any-of-three", "name": "Any of Three", "ins": ["A", "B", "C"], "outs": ["Y"],
     "goal": "Lamp Y lights when at least one of the three switches is on.",
     "fn": lambda v: {"Y": v["A"] | v["B"] | v["C"]},
     "ref": "t = or(A, B); Y := or(t, C)", "unlock": "or3", "label": "OR 3",
     "nudge": "Same idea as Three Keys, with a different gate.",
     "hint": "OR two switches, then OR that with the third.",
     "log": "Smoke alarm bus. Any one detector is enough to wake the corridor."},
    {"id": "lock-code", "name": "Lock Code", "ins": ["A", "B", "C"], "outs": ["Y"],
     "goal": "Lamp Y lights only for one pattern: A on, B off, C on.",
     "fn": lambda v: {"Y": v["A"] & (1 - v["B"]) & v["C"]},
     "ref": "nb = not(B); t = and(A, nb); Y := and(t, C)", "unlock": None,
     "nudge": "A switch that must be off can be flipped by a NOT first.",
     "hint": "Turn B into 'B is off' with a NOT, then AND it with A and with C.",
     "log": "A keypad that opens for exactly one code. The code was never changed from the factory one."},
    {"id": "selector", "name": "Selector", "ins": ["A", "B", "S"], "outs": ["Y"],
     "goal": "Lamp Y copies switch A when S is off and switch B when S is on.",
     "fn": lambda v: {"Y": v["B"] if v["S"] else v["A"]},
     "ref": "n = not(S); p = and(A, n); q = and(B, S); Y := or(p, q)", "unlock": "mux2", "label": "MUX 2:1",
     "nudge": "Let exactly one of A and B through, depending on S.",
     "hint": "AND A with NOT S, AND B with S, then OR the two results together.",
     "log": "Two cameras, one monitor. The selector decides what the station gets to see."},
    {"id": "majority", "name": "Majority", "ins": ["A", "B", "C"], "outs": ["Y"],
     "goal": "Lamp Y lights when at least two of the three switches are on.",
     "fn": lambda v: {"Y": 1 if v["A"] + v["B"] + v["C"] >= 2 else 0},
     "ref": "ab = and(A, B); o = or(A, B); c = and(C, o); Y := or(ab, c)", "unlock": "maj3", "label": "MAJORITY",
     "nudge": "Two out of three: either A and B agree, or C agrees with one of them.",
     "hint": "(A AND B) OR (C AND (A OR B)). That is four chips.",
     "log": "Three redundant sensors vote. Vale trusted the vote until the day two of them were wrong together."},
    {"id": "exactly-one", "name": "Exactly One", "ins": ["A", "B", "C"], "outs": ["Y"],
     "goal": "Lamp Y lights when exactly one switch is on, not none, not two, not three.",
     "fn": lambda v: {"Y": 1 if v["A"] + v["B"] + v["C"] == 1 else 0},
     "ref": "x = xor(A, B); p = xor(x, C); ab = and(A, B); n = nand(ab, C); Y := and(p, n)",
     "unlock": "one3", "label": "EXACTLY ONE",
     "nudge": "Chaining XORs lights the lamp for one or three switches on. Something must rule out all three.",
     "hint": "XOR A and B, then XOR with C. Separately NAND (A AND B) with C. AND those two results.",
     "log": "A lock-out: only one operator at a console at a time. The log shows two, once."},
    {"id": "four-way-selector", "name": "Four-Way Selector", "ins": ["D0", "D1", "D2", "D3", "S1", "S0"], "outs": ["Y"],
     "goal": "Lamp Y copies the data switch picked by the two-bit number S1 S0 (00 picks D0, 01 picks D1, 10 picks D2, 11 picks D3).",
     "fn": lambda v: {"Y": v[f"D{2 * v['S1'] + v['S0']}"]},
     "ref": "m0 = mux2(D0, D1, S0); m1 = mux2(D2, D3, S0); Y := mux2(m0, m1, S1)", "unlock": "mux4", "label": "MUX 4:1",
     "nudge": "You already built a two-way selector. Selectors can feed selectors.",
     "hint": "Two MUX 2:1 chips pick between D0/D1 and D2/D3 using S0. A third picks between their outputs using S1.",
     "log": "Four feeds, one screen. Vale kept camera 3 pointed at the cooling room. Nobody asked why."},
    {"id": "comparator", "name": "Comparator", "ins": ["A", "B"], "outs": ["LT", "EQ", "GT"],
     "goal": "Lamp LT lights when A is less than B, EQ when they are equal, GT when A is greater (as numbers 0 and 1).",
     "fn": lambda v: {"LT": 1 if v["A"] < v["B"] else 0, "EQ": 1 if v["A"] == v["B"] else 0, "GT": 1 if v["A"] > v["B"] else 0},
     "ref": "x = xor(A, B); LT := and(B, x); GT := and(A, x); EQ := xnor(A, B)", "unlock": "cmp1", "label": "COMPARE",
     "nudge": "When the bits differ, the one that is on is the bigger one.",
     "hint": "XOR says they differ. B AND that means B is bigger (LT). A AND that means A is bigger (GT). XNOR is EQ.",
     "log": "Which reading is higher: the sensor, or the number Vale wrote down? The comparator does not take sides."},
    {"id": "decoder", "name": "Decoder", "ins": ["A", "B"], "outs": ["Y0", "Y1", "Y2", "Y3"],
     "goal": "Exactly one lamp lights, numbered by the two-bit number A B: 00 lights Y0, 01 lights Y1, 10 lights Y2, 11 lights Y3.",
     "fn": lambda v: {f"Y{k}": 1 if 2 * v["A"] + v["B"] == k else 0 for k in range(4)},
     "ref": "na = not(A); nb = not(B); Y0 := and(na, nb); Y1 := and(na, B); Y2 := and(A, nb); Y3 := and(A, B)",
     "unlock": "dec2", "label": "DECODER",
     "nudge": "Each lamp is a Lock Code for one pattern.",
     "hint": "Make NOT A and NOT B once. Each lamp is an AND of one choice from A (A or NOT A) and one from B.",
     "log": "A switchboard: a number goes in, one door opens. Chapter two done."},
]
