/*
 * Layout preference (PC version plan, planning/PC-VERSION-PLAN.md section 3.1).
 *
 * A game with a Desktop boot has two entry pages over the same game code and
 * the same saves: the Classic page (index.html) and the Desktop page
 * (pc.html, generated by scripts/generate-pc-pages.py). The player chooses
 * BEFORE the game loads, so only one of them ever boots. This script is the
 * first one in <head> of both pages:
 *
 *   <script src="../../shared/layout-pref.js" data-game-id="continuum"
 *           data-pc-page="pc.html" data-classic-page="index.html"></script>
 *
 * - On the Classic page: if the stored preference for this game is "pc" and
 *   this window is desktop-class (wide, mouse-like pointer), it redirects to
 *   the Desktop page before anything heavy loads (Pyodide is not fetched).
 * - On the Desktop page (it sets window.NOYVJ_LAYOUT = "pc" first): landing
 *   there is itself the choice, so it records "pc".
 * - window.NoyvjLayout lets the opening screen (and the Desktop menu) offer
 *   "Switch to ..." without knowing anything about either page.
 *
 * The preference is a per-browser display choice, not part of any save.
 */
(function () {
  "use strict";
  const script = document.currentScript;
  if (!script || !script.dataset.gameId || !script.dataset.pcPage) return;
  const gameId = script.dataset.gameId;
  const pcPage = script.dataset.pcPage;
  const classicPage = script.dataset.classicPage || "index.html";
  const KEY = "layout-pref:" + gameId;
  const isPc = window.NOYVJ_LAYOUT === "pc";
  const DESKTOP_QUERY = "(min-width: 960px) and (hover: hover) and (pointer: fine)";

  const get = () => { try { return localStorage.getItem(KEY); } catch (e) { return null; } };
  const set = (v) => { try { localStorage.setItem(KEY, v); } catch (e) { /* convenience only */ } };
  const capable = () => { try { return window.matchMedia(DESKTOP_QUERY).matches; } catch (e) { return false; } };

  if (!isPc && get() === "pc" && capable()) {
    location.replace(pcPage + location.search + location.hash);
    return;
  }
  if (isPc) set("pc");

  window.NoyvjLayout = {
    current: isPc ? "pc" : "classic",
    capable,
    // Records the choice and loads the other boot (the save carries over).
    switchTo(layout) {
      set(layout === "pc" ? "pc" : "classic");
      location.href = (layout === "pc" ? pcPage : classicPage) + location.hash;
    },
  };
})();
