#!/usr/bin/env python3
"""Generate sitemap.xml, robots.txt and the schema.org JSON-LD (TODO Y-8).

Run from anywhere:  python3 scripts/generate-seo.py   (add --check to verify only; writes nothing)

Outputs (all committed; re-run when a game is added or a public page appears):
  sitemap.xml            the public hub pages plus one entry per hub-linked game (games/<slug>/)
  robots.txt             allows everything public and points at the sitemap. It deliberately does NOT
                         name the owner-only pages (admin.html, ideas.html, warframe_build_tracker/):
                         a Disallow line is a public advertisement of the very URL it hides. Those
                         pages are kept out of search by their own `noindex, nofollow` meta tag and
                         the owner gate, and are never in the sitemap.
  share/jsonld/<slug>.json   one VideoGame + WebApplication object per game, for the main session to
                         inline into each game page as <script type="application/ld+json">
  index.html             a @graph (WebSite + an ItemList of every game) between
                         `<!-- seo-jsonld:start -->` and `<!-- seo-jsonld:end -->`, refreshed in place

Facts come from the repo, never typed here: the game list, names, blurbs and tags from the lobby cards in
index.html (limited to slugs in game-manifest.json), added/updated dates from game-added.json and
game-last-updated.json, session length from game-sessions.json. The base URL is
https://noyvj.github.io/NoyvjGames/ (git remote noyvj/NoyvjGames, and the backend's CORS origin).
No aggregateRating is emitted: ratings live in the backend, and a rating copied into static markup would go
stale and could be read as fabricated. Add one only from live data.

IMPORTANT, honest limits:
  * GitHub Pages serves a project site under /NoyvjGames/, and crawlers only read robots.txt at the
    HOST root (https://noyvj.github.io/robots.txt), which this repo does not control. So robots.txt here is
    documentation plus a Sitemap pointer; the sitemap itself must be submitted in Search Console (below)
    or found through links. A custom domain pointed at Pages would make robots.txt effective.
  * Page `lastmod` values come from `git log` and are omitted for files with no commit yet.

SEARCH CONSOLE (owner step, NOT done here; no token has been supplied):
  1. In Google Search Console add the property https://noyvj.github.io/NoyvjGames/ (URL-prefix type).
  2. Choose the "HTML file" verification method and download the file google<token>.html it offers.
  3. Put that file in the repo root (or add the offered <meta name="google-site-verification" ...> tag to
     index.html instead), commit and push, then press Verify.
  4. Submit https://noyvj.github.io/NoyvjGames/sitemap.xml under Sitemaps.
  Placeholder to fill: GOOGLE_SITE_VERIFICATION_TOKEN = None  (a FOR-YOU entry owns this step).
"""

import json
import re
import subprocess
import sys
from pathlib import Path
from xml.sax.saxutils import escape

sys.path.insert(0, str(Path(__file__).resolve().parent))
import sitedata  # noqa: E402

GOOGLE_SITE_VERIFICATION_TOKEN = None  # owner supplies this; see the docstring

JSONLD_START = "<!-- seo-jsonld:start (generated by scripts/generate-seo.py) -->"
JSONLD_END = "<!-- seo-jsonld:end -->"
SESSION_DURATION = {"short": "PT5M", "medium": "PT20M"}  # "long" is open-ended: no timeRequired
TAG_GENRES = {
    "climate": "Climate simulation", "space": "Space", "civilization": "Civilization building",
    "economy": "Economy", "language-learning": "Language learning", "deep-systems": "Systems simulation",
    "quick": "Short session",
}
AUTHOR = {"@type": "Person", "name": "Noyvj", "url": "https://github.com/noyvj"}


def git_date(path):
    try:
        out = subprocess.run(["git", "log", "-1", "--format=%cs", "--", str(path)], cwd=sitedata.ROOT,
                             capture_output=True, text=True, timeout=20).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None
    return out or None


def game_jsonld(game, context=True):
    data = {
        "@context": "https://schema.org",
        "@type": ["VideoGame", "WebApplication"],
        "name": game["name"],
        "description": game["blurb"],
        "url": sitedata.game_url(game["slug"]),
        "image": sitedata.share_image_url(game["slug"]),
        "applicationCategory": "GameApplication",
        "operatingSystem": "Any modern web browser",
        "browserRequirements": "Requires JavaScript and WebAssembly",
        "gamePlatform": "Web browser",
        "playMode": "SinglePlayer",
        "inLanguage": ["en", "fr"] if game["slug"] == "champ-de-mots" else "en",
        "isAccessibleForFree": True,
        "offers": {"@type": "Offer", "price": "0", "priceCurrency": "USD"},
        "author": AUTHOR,
        "publisher": {"@type": "Organization", "name": sitedata.SITE_NAME, "url": sitedata.BASE_URL},
        "genre": [TAG_GENRES[t] for t in game["tags"] if t in TAG_GENRES],
    }
    if game["added"]:
        data["dateCreated"] = game["added"]
    if game["updated"]:
        data["dateModified"] = game["updated"]
    if game["session"] in SESSION_DURATION:
        data["timeRequired"] = SESSION_DURATION[game["session"]]
    if not context:
        del data["@context"]
    return data


def hub_jsonld(games):
    return {
        "@context": "https://schema.org",
        "@graph": [
            {"@type": "WebSite", "name": sitedata.SITE_NAME, "url": sitedata.BASE_URL,
             "description": sitedata.hub_description(games), "inLanguage": "en", "image": sitedata.BASE_URL + "share/hub.png"},
            {"@type": "ItemList", "name": "NoyvjGames", "numberOfItems": len(games),
             "itemListElement": [{"@type": "ListItem", "position": i + 1, "item": game_jsonld(g, context=False)}
                                 for i, g in enumerate(games)]},
        ],
    }


def sitemap(games):
    rows = []
    for filename, _title, _desc, listed in sitedata.PUBLIC_PAGES:
        if not listed or not (sitedata.ROOT / filename).exists():
            continue
        rows.append((sitedata.page_url(filename), git_date(filename), "weekly" if filename in ("index.html", "whats-new.html") else "monthly",
                     "1.0" if filename == "index.html" else "0.6"))
    for game in games:
        rows.append((sitedata.game_url(game["slug"]), game["updated"], "weekly", "0.8"))
    lines = ['<?xml version="1.0" encoding="UTF-8"?>', '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for url, lastmod, freq, prio in rows:
        lines += ["  <url>", f"    <loc>{escape(url)}</loc>"]
        if lastmod:
            lines.append(f"    <lastmod>{lastmod}</lastmod>")
        lines += [f"    <changefreq>{freq}</changefreq>", f"    <priority>{prio}</priority>", "  </url>"]
    lines.append("</urlset>")
    return "\n".join(lines) + "\n"


def robots():
    return (
        "# robots.txt for NoyvjGames. Crawlers only read this at the host root, so for a GitHub Pages\n"
        "# project site it is documentation plus a sitemap pointer (see scripts/generate-seo.py).\n"
        "# Owner-only pages are protected by their own noindex meta tag and gate, not by naming them here.\n"
        "User-agent: *\n"
        "Allow: /\n"
        "\n"
        f"Sitemap: {sitedata.BASE_URL}sitemap.xml\n"
    )


def inject_jsonld(text, payload):
    block = (JSONLD_START + '\n<script type="application/ld+json" id="hub-jsonld">\n'
             + json.dumps(payload, separators=(",", ":"), ensure_ascii=False).replace("</", "<\\/")
             + "\n</script>\n" + JSONLD_END + "\n")
    pattern = re.compile(re.escape(JSONLD_START) + r".*?" + re.escape(JSONLD_END) + r"\n?", re.S)
    text = pattern.sub("", text, count=1)
    # Right after </title>: the shared includes must stay last in <head> (shared/tests/test_site_includes.py).
    anchor = r"(<!-- share-meta:end -->\n)" if "<!-- share-meta:end -->" in text else r"(</title>\n)"
    return re.sub(anchor, lambda m: m.group(1) + block, text, count=1)


def main(argv):
    check = "--check" in argv
    games = sitedata.load_games()
    if not games:
        sys.exit("No games found in index.html / game-manifest.json.")
    outputs = {"sitemap.xml": sitemap(games), "robots.txt": robots()}
    for game in games:
        outputs[f"share/jsonld/{game['slug']}.json"] = json.dumps(game_jsonld(game), indent=2, ensure_ascii=False) + "\n"
    index = sitedata.ROOT / "index.html"
    outputs["index.html"] = inject_jsonld(index.read_text(encoding="utf-8"), hub_jsonld(games))
    stale = []
    for rel, text in outputs.items():
        path = sitedata.ROOT / rel
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(rel)
            if not check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
    if check:
        print("Out of date: " + ", ".join(stale) if stale else "Up to date")
    else:
        print("Wrote: " + (", ".join(stale) or "nothing changed"))
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
