#!/usr/bin/env python3
"""Generate each game's Desktop boot (games/<slug>/pc.html) from its Classic
page (games/<slug>/index.html). See planning/PC-VERSION-PLAN.md.

pc.html is never edited by hand: it is index.html plus a fixed set of
additions, so the two pages cannot drift apart (every element id game.py looks
up exists in both). Run after changing a game's index.html or the config below:

    python3 scripts/generate-pc-pages.py          # rewrite pc.html files
    python3 scripts/generate-pc-pages.py --check  # exit 1 if any is stale

Additions made to the Classic markup:
  - <html data-layout="pc"> and a "(Desktop)" title suffix
  - window.NOYVJ_LAYOUT = "pc" before any other script (game code reads it)
  - shared/pc-shell.css, then the game's own pc.css, after style.css
  - per-game config from games/<slug>/pc-config.json (see planning/PC-GAME-CONVERSION-GUIDE.md): the
    list of panels that become windows (window.NOYVJ_PC_WINDOWS) and the
    zones existing elements are moved into (window.NOYVJ_PC_ZONES)
  - the game's own pc.js (if any) right after that, and shared/pc-shell.js at the end of <body>
The Classic page itself carries one extra line, the layout-pref.js script tag,
which redirects a player who chose Desktop and lets the opening screen switch.
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def load_configs():
    """Every game with a games/<slug>/pc-config.json gets a Desktop boot. The config is the only
    per-game input besides the game's own pc.css / pc.js, so converting a game never edits this file."""
    configs = {}
    for path in sorted((ROOT / "games").glob("*/pc-config.json")):
        configs[path.parent.name] = json.loads(path.read_text(encoding="utf-8"))
    return configs


BANNER = "<!-- GENERATED by scripts/generate-pc-pages.py from index.html. Do not edit by hand. -->\n"


def build(slug, cfg):
    html = (ROOT / "games" / slug / "index.html").read_text(encoding="utf-8")
    out = html
    out = out.replace('<html lang="en">', '<html lang="en" data-layout="pc">', 1)
    out = re.sub(r"<title>([^<]*)</title>", lambda m: f"<title>{m.group(1)} (Desktop)</title>", out, count=1)
    windows = json.dumps(
        [{"panel": p, "toggle": t, "title": title} for p, t, title in cfg["windows"]], ensure_ascii=False
    )
    anchor = re.search(r'<meta name="viewport"[^>]*>', out)
    zones = json.dumps(cfg.get("zones", {}), ensure_ascii=False)
    hints = json.dumps(cfg.get("hints", []), ensure_ascii=False)
    notify = json.dumps(cfg.get("notify"), ensure_ascii=False)
    toolbar = json.dumps(cfg.get("toolbar"), ensure_ascii=False)
    composites = json.dumps(cfg.get("composites", []), ensure_ascii=False)
    adopt = json.dumps(cfg.get("adopt", []), ensure_ascii=False)
    readouts = json.dumps(cfg.get("readouts", []), ensure_ascii=False)
    side_label = json.dumps(cfg.get("side_label", "Details"), ensure_ascii=False)
    inject = (f'\n<script>window.NOYVJ_LAYOUT = "pc"; window.NOYVJ_PC_WINDOWS = {windows}; '
              f'window.NOYVJ_PC_ZONES = {zones}; window.NOYVJ_PC_HINTS = {hints}; '
              f'window.NOYVJ_PC_NOTIFY = {notify}; window.NOYVJ_PC_TOOLBAR = {toolbar}; '
              f'window.NOYVJ_PC_COMPOSITES = {composites}; window.NOYVJ_PC_ADOPT = {adopt}; '
              f'window.NOYVJ_PC_READOUTS = {readouts}; window.NOYVJ_PC_SIDE_LABEL = {side_label};</script>')
    if (ROOT / "games" / slug / "pc.js").exists():
        inject += '\n<script src="pc.js"></script>'
    out = out[: anchor.end()] + inject + out[anchor.end():]
    css = '<link rel="stylesheet" href="style.css">'
    extra = f'{css}\n<link rel="stylesheet" href="../../shared/pc-shell.css">'
    if (ROOT / "games" / slug / "pc.css").exists():
        extra += '\n<link rel="stylesheet" href="pc.css">'
    out = out.replace(css, extra, 1)
    out = out.replace("</body>", '<script src="../../shared/pc-shell.js"></script>\n</body>', 1)
    return out.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + BANNER, 1)


def main():
    check = "--check" in sys.argv
    stale = []
    for slug, cfg in load_configs().items():
        target = ROOT / "games" / slug / "pc.html"
        text = build(slug, cfg)
        if check:
            if not target.exists() or target.read_text(encoding="utf-8") != text:
                stale.append(slug)
        else:
            target.write_text(text, encoding="utf-8")
            print(f"wrote {target.relative_to(ROOT)}")
    if stale:
        print("stale pc.html: " + ", ".join(stale) + " (run scripts/generate-pc-pages.py)")
        sys.exit(1)


if __name__ == "__main__":
    main()
