#!/usr/bin/env python3
"""Rewrites the progress line and the per-section percentage chart at the top of planning/TODO.md.

Run it after ticking items:  python3 scripts/todo-progress.py
  --check   exit 1 if the chart or the Progress line is out of date (changes nothing)

A section is a "## " heading; its percentage is checked boxes over all boxes under it (lines starting with
"- [ ]" or "- [x]", indented or not). The chart sits between the two marker comments below, right after the
Progress line, and is regenerated from scratch every run, so never edit it by hand.
"""
import re
import sys
from pathlib import Path

TODO = Path(__file__).resolve().parent.parent / "planning" / "TODO.md"
START = "<!-- PROGRESS-CHART:START (generated by scripts/todo-progress.py, do not edit) -->"
END = "<!-- PROGRESS-CHART:END -->"
BOX = re.compile(r"^\s*- \[([ x])\]")


def sections(text):
    out, cur = [], None
    for line in text.splitlines():
        m = re.match(r"^## (.+)$", line)
        if m:
            cur = [m.group(1).strip(), 0, 0]
            out.append(cur)
            continue
        b = BOX.match(line)
        if b and cur is not None:
            cur[2] += 1
            if b.group(1) == "x":
                cur[1] += 1
    return [s for s in out if s[2]]


def short(name):
    name = re.sub(r"\s*\(.*$", "", name)  # drop trailing parentheses
    name = re.sub(r"\s+\(.*", "", name)
    return name[:48].strip().rstrip(".,;:")


def bar(pct, width=10):
    filled = int(round(pct / 100 * width))
    return "█" * filled + "░" * (width - filled)


def chart(secs):
    total = sum(s[2] for s in secs)
    done = sum(s[1] for s in secs)
    rows = ["| Section | Done | % | |", "|---|---:|---:|---|"]
    for name, d, a in sorted(secs, key=lambda s: (-(s[1] / s[2]), -s[2])):
        pct = d / a * 100
        rows.append(f"| {short(name)} | {d}/{a} | {pct:.0f}% | {bar(pct)} |")
    rows.append(f"| **All sections** | **{done}/{total}** | **{done / total * 100:.1f}%** | {bar(done / total * 100)} |")
    return done, total, "\n".join(rows)


def main():
    check = "--check" in sys.argv
    text = TODO.read_text(encoding="utf-8")
    done, total, table = chart(sections(text))
    prog = f"**Progress: {done}/{total} items checked off ({done / total * 100:.1f}%).**"
    block = f"{START}\n\n**Per-section progress (finished sections first):**\n\n{table}\n\n{END}"
    new = re.sub(r"\*\*Progress: \d+/\d+ items checked off \([\d.]+%\)\.\*\*", prog, text, count=1)
    if START in new:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), lambda m: block, new, count=1, flags=re.S)
    else:
        i = new.index(prog) + len(prog)
        j = new.index("\n", i)  # end of the progress line (its trailing text stays on that line)
        new = new[: j + 1] + "\n" + block + "\n" + new[j + 1:]
    if check:
        sys.exit(0 if new == text else 1)
    TODO.write_text(new, encoding="utf-8")
    print(f"{done}/{total} ({done / total * 100:.1f}%), {len(sections(text))} sections")


if __name__ == "__main__":
    main()
