"""Chapter 1, Moving: straight corridors. The robot cannot turn yet, so every room is a line."""

ROOMS = [
    {"id": "wake-up", "name": "Wake Up", "allow": "F",
     "rows": ["######", ">..E##", "######"],
     "ref": "main: F F F", "par": 3,
     "nudge": "The robot walks one tile for each Forward. Count the tiles to the glowing pad.",
     "intro": "Power returns to the maintenance deck, one dim light at a time."},
    {"id": "long-hall", "name": "Long Hall", "allow": "F",
     "rows": ["#########", ">......E#", "#########"],
     "ref": "main: F F F F F F F", "par": 7,
     "nudge": "Seven tiles to cross. There is no shortcut yet, only patience.",
     "intro": "The corridor was built for a crew of two hundred. Nobody told the robot."},
    {"id": "stop-short", "name": "Stop Short", "allow": "F",
     "rows": ["#v#", "#.#", "#.#", "#E#", "#.#", "#.#"],
     "ref": "main: F F F", "par": 3,
     "nudge": "The pad is not at the end of the hall. The robot has to stop on it, not run past it.",
     "intro": "A service shaft. The pad sits halfway down, like a bad joke."},
    {"id": "first-switch", "name": "First Switch", "allow": "F S",
     "rows": ["########", ">.1.AE.#", "########"],
     "ref": "main: F F S F F F", "par": 6,
     "nudge": "The door is shut until the switch is lit. Stand on the switch and use Switch.",
     "intro": "A door with a lock that the station never fixed. The switch next to it still works."},
    {"id": "first-delivery", "name": "First Delivery", "allow": "F G P",
     "rows": ["#########", ">.p.o.E.#", "#########"],
     "ref": "main: F F G F F P F F", "par": 8,
     "nudge": "Pick the part up on its tile, carry it forward, and place it in the socket. Then go on to the pad.",
     "intro": "Somebody left a power cell on the floor. The socket two tiles on needs it."},
    {"id": "in-order", "name": "In Order", "allow": "F G P S",
     "rows": ["##########", ">p.1Ao.E.#", "##########"],
     "ref": "main: F G F F S F F P F F", "par": 10,
     "nudge": "The part is right next to you. Take it first, then light the switch to open the door in your way.",
     "intro": "Order matters. The robot does not improvise, which is the whole problem."},
    {"id": "the-shaft", "name": "The Shaft", "allow": "F G P S",
     "rows": ["#v#", "#1#", "#.#", "#A#", "#p#", "#2#", "#B#", "#o#", "#.#", "#E#"],
     "ref": "main: F S F F F G F S F F P F F", "par": 13,
     "nudge": "Two switches, two doors, one part. Work from the top: switch, door, part, switch, door, socket, pad.",
     "intro": "The last straight run. After this the corridors start to bend."},
]
