"""Chapter 5, Conditionals: `until` (keep going until something is true) and `if ... else` (do one thing or the other). The robot looks at its own tile and at what is ahead."""

ROOMS = [
    {"id": 'walk-to-the-wall', "name": 'Walk to the Wall', "allow": 'F L R G P S rep until if A B',
     "rows": ['#########', '>.......E', '#########'],
     "ref": 'main: until blocked { F }', "par": 2,
     "nudge": 'An until block keeps repeating its steps until its condition is true. Walk forward until the way ahead is blocked.',
     "intro": 'A hall that ends in a wall. The robot has no idea how long it is, which is the point.'},
    {"id": 'find-the-part', "name": 'Find the Part', "allow": 'F L R G P S rep until if A B',
     "rows": ['##########', '>.....p..E', '##########'],
     "ref": 'main: until part { F } G until blocked { F }', "par": 5,
     "nudge": 'Walk until there is a part on your tile, pick it up, then walk until the way is blocked.',
     "intro": 'The part is somewhere along the hall. The robot is not told where. It finds out by standing on it.'},
    {"id": 'sweep', "name": 'Sweep', "allow": 'F L R G P S rep until if A B',
     "rows": ['##########', '>.1..2.3.E', '##########'],
     "ref": 'main: rep 9 { F if switch { S } }', "par": 4,
     "nudge": 'Take a step, and light a switch only if there is an unlit one on your tile. Nine steps in a repeat do it all.',
     "intro": 'Three switches in no sensible pattern. An if block does not need a pattern.'},
    {"id": 'carry-home', "name": 'Carry Home', "allow": 'F L R G P S rep until if A B',
     "rows": ['#v#', '#.#', '#.#', '#p#', '#.#', '#.#', '#.#', '#o#', '#.#', '#E#'],
     "ref": 'main: until part { F } G until socket { F } P until blocked { F }', "par": 8,
     "nudge": 'Walk until there is a part, pick it up, walk until there is a socket, place it, then walk until blocked.',
     "intro": "One part, one socket and a pad, far apart. The distances are the robot's problem."},
    {"id": 'irregular-deliveries', "name": 'Irregular Deliveries', "allow": 'F L R G P S rep until if A B',
     "rows": ['#v#', '#.#', '#p#', '#o#', '#.#', '#.#', '#p#', '#.#', '#o#', '#E#'],
     "ref": 'main: until blocked { F if part { G } if socket { P } }', "par": 6,
     "nudge": 'One list for the whole shaft: step forward, pick up if there is a part, place if there is a socket, and keep going until blocked.',
     "intro": 'The parts and sockets are scattered. A list that checks as it goes does not care.'},
    {"id": 'snake', "name": 'Snake', "allow": 'F L R G P S rep until if A B',
     "rows": ['>....#####', '####.#####', '####....##', '#######.##', '#######..E'],
     "ref": 'main: rep 2 { until blocked { F } R until blocked { F } L } until blocked { F }', "par": 9,
     "nudge": 'Every straight stretch ends at a wall. Walk until blocked, turn, and alternate right and left. A repeat holds one right and one left.',
     "intro": 'A pipe that bends back on itself, built by someone who never learned to draw a straight line.'},
    {"id": 'wall-hugger', "name": 'Wall Hugger', "allow": 'F L R G P S rep until if A B',
     "rows": ['>......', '######.', '.....#.', '.#E#.#.', '.#...#.', '.#####.', '.......'],
     "ref": 'main: until exit { if blocked { R } else { F } }', "par": 4,
     "nudge": 'The corridor spirals inwards and every turn is a right turn. Until you are on the exit: turn right if blocked, otherwise step forward.',
     "intro": 'A spiral that ends in the middle. Four steps of program, thirty of walking.'},
]
