"""Chapter 2, Turning: the robot learns left and right. Par is the true minimum number of actions (the tests check it with a breadth-first search)."""

ROOMS = [
    {"id": 'around-the-corner', "name": 'Around the Corner', "allow": "F L R G P S",
     "rows": ['>..#', '##.#', '##E#'],
     "ref": 'main: F F R F F', "par": 5,
     "nudge": 'The robot turns where you tell it to, a quarter turn at a time. Walk the hall, turn, and walk down to the pad.',
     "intro": "A hallway with a bend in it. The first of many, the deck's architects were fond of them."},
    {"id": 'detour', "name": 'Detour', "allow": "F L R G P S",
     "rows": ['>.#.E', '..#..', '.....'],
     "ref": 'main: F R F F L F F F L F F', "par": 11,
     "nudge": 'The wall is in the way, so go round it: down, along the bottom, and back up to the pad.',
     "intro": 'Somebody put a wall exactly where the straight line used to be.'},
    {"id": 'part-on-the-bend', "name": 'Part on the Bend', "allow": "F L R G P S",
     "rows": ['>.##', '#.##', '#p..', '##.o', '##.E'],
     "ref": 'main: F R F F L G F F R F P F', "par": 12,
     "nudge": 'Walk down to the part, pick it up, then follow the bend to the socket before the pad.',
     "intro": 'A power cell, left on a corner. Housekeeping stopped coming years ago.'},
    {"id": 'switch-behind-the-wall', "name": 'Switch Behind the Wall', "allow": "F L R G P S",
     "rows": ['>.#####', '#.#...E', '#1#.##A', '#......'],
     "ref": 'main: F R F F S F L F F F F F L F F', "par": 15,
     "nudge": 'The switch has to be lit, and it is not on the way to the pad. Go and light it, then find the pad.',
     "intro": 'The switch is down the other corridor. The robot does not mind. It has no opinions.'},
    {"id": 's-bend', "name": 'S-Bend', "allow": "F L R G P S",
     "rows": ['>..#...', '##.#.#.', '##...#E'],
     "ref": 'main: F F R F F L F F L F F R F F R F F', "par": 17,
     "nudge": 'Follow the corridor and turn at every corner: right, left, left, right, right.',
     "intro": 'A pipe in the shape of a pipe. The deck was built by someone with a sense of humour, or none.'},
    {"id": 'turn-around', "name": 'Turn Around', "allow": "F L R G P S",
     "rows": ['#######', '>pp.oo.', '#######'],
     "ref": 'main: F G F F F L L P F F L L G F F F P', "par": 17,
     "nudge": 'You can carry one part at a time. Take one to its socket, come back for the other, and turn around with two turns.',
     "intro": 'Two parts, two sockets, one pair of hands.'},
    {"id": 'the-long-way-round', "name": 'The Long Way Round', "allow": "F L R G P S",
     "rows": ['>.#..p#', '..#.#.#', '..1.#.#', '###A#.#', '#E...o#'],
     "ref": 'main: F R F F L F S F L F F R F F R G F F F F R P F F F F', "par": 26,
     "nudge": 'Light the switch first, then go and fetch the part, bring it to the socket and finish on the pad.',
     "intro": 'The longest corridor yet. It goes everywhere and arrives eventually.'},
]
