"""Chapter 6, The Long Shift: everything at once. The last room clears the deck and opens the sandbox."""

ROOMS = [
    {"id": 'locked-stores', "name": 'Locked Stores', "allow": 'F L R G P S rep until if A B',
     "rows": ['##>1', '###.', '###p', '###A', '##.o', '##.#', '##p#', '##.#', 'E.o#'],
     "ref": 'main: F S R A L A F\nA: F F G F F P R F', "par": 15,
     "nudge": 'Light the switch to open the door. Then the same delivery happens twice: call it as a routine, with a turn between.',
     "intro": 'The stores were locked years ago. The key was a switch the whole time.'},
    {"id": 'cold-storage', "name": 'Cold Storage', "allow": 'F L R G P S rep until if A B',
     "rows": ['>.1p.o', '#####.', '#####2', '#####p', '#####.', 'o.p3.o', 'E#####'],
     "ref": 'main: A R A R A L F\nA: F F S F G F F P', "par": 15,
     "nudge": 'One walk does a switch, a pick-up and a delivery. It happens three times with turns between, so it wants a routine.',
     "intro": 'Cold storage, three shelves, one tired robot.'},
    {"id": 'night-round', "name": 'Night Round', "allow": 'F L R G P S rep until if A B',
     "rows": ['>1#######', '#.#######', '#.po#####', '###..po##', '######..E'],
     "ref": 'main: A rep 2 { B F } F\nA: F S R F F L\nB: F G F P R F L', "par": 18,
     "nudge": 'Two routines: one lights a switch on the way, the other makes a delivery. The second one is used twice inside a repeat.',
     "intro": "The night round. It was somebody's job once, and now it is the robot's, and the robot is thorough."},
    {"id": 'the-sweeper', "name": 'The Sweeper', "allow": 'F L R G P S rep until if A B',
     "rows": ['##########', '>1popo.A.E', '##########'],
     "ref": 'main: rep 9 { F if switch { S } if part { G } if socket { P } }', "par": 8,
     "nudge": 'One list can do every kind of job if it checks its own tile each step: switch, part, socket. Nine steps down the hall.',
     "intro": 'A hall with a bit of everything. Instead of planning it, the robot just checks.'},
    {"id": 'last-lap', "name": 'Last Lap', "allow": 'F L R G P S rep until if A B',
     "rows": ['>......', '######.', '.....#.', 'A#E#.#1', 'o#...#.', '.#####.', '..p....'],
     "ref": 'main: until exit { if switch { S } if part { G } if socket { P } if blocked { R } else { F } }', "par": 10,
     "nudge": 'The spiral again, with a switch, a door, a part and a socket along the way. Check each tile for each job, then turn if blocked, else step.',
     "intro": 'The last room on the deck. When it is done the lights stay on, and nobody has to say thank you.'},
]
