"""Chapter 3, Loops: `rep N { ... }`. Par is the length of the reference list; every room is much longer written out step by step."""

ROOMS = [
    {"id": "staircase", "name": "Staircase", "allow": "F L R G P S rep",
     "rows": [">.###", "#..##", "##..#", "###..", "####E"],
     "ref": "main: rep 4 { F R F L }", "par": 5,
     "nudge": "The same four moves repeat all the way down: forward, right, forward, left. Put them in a repeat block.",
     "intro": "A staircase for a robot that cannot climb. It goes down instead, and so does morale."},
    {"id": "three-switches", "name": "Three Switches", "allow": "F L R G P S rep",
     "rows": ["########", ">.1.2.3E", "########"],
     "ref": "main: rep 3 { F F S } F", "par": 5,
     "nudge": "Every switch is two tiles on from the last one. Repeat forward, forward, switch three times, then step onto the pad.",
     "intro": "Three switches in a row. Whoever laid them out wanted to be thanked for it."},
    {"id": "the-conveyor", "name": "The Conveyor", "allow": "F L R G P S rep",
     "rows": ["##########", ">p.op.op.o", "##########"],
     "ref": "main: rep 3 { F G F F P }", "par": 6,
     "nudge": "Each part is picked up one tile on and placed in the socket two tiles after that. Do that once, then repeat it.",
     "intro": "A conveyor line that stopped delivering a decade ago. The parts are still there. So is the robot."},
    {"id": "lap", "name": "Lap", "allow": "F L R G P S rep",
     "rows": [">....", "####.", "####.", "####.", "E...."],
     "ref": "main: rep 2 { rep 4 { F } R } rep 4 { F }", "par": 6,
     "nudge": "Four forward and a turn, twice, and four more forward at the end. A repeat can sit inside another repeat.",
     "intro": "A perimeter walk. Nothing has ever tried to cross the inside; it is mostly wall."},
    {"id": "switch-lap", "name": "Switch Lap", "allow": "F L R G P S rep",
     "rows": [">...1", "####.", ".###.", "E###.", "3...2"],
     "ref": "main: rep 3 { rep 4 { F } S R } F", "par": 6,
     "nudge": "Three corners, three switches. Each time: four forward, light the switch, turn right. Then one step to the pad.",
     "intro": "Switches at the corners, because someone thought corners needed attention."},
    {"id": "parts-shuttle", "name": "Parts Shuttle", "allow": "F L R G P S rep",
     "rows": [">p.p.p.", ".o.o.o."],
     "ref": "main: rep 3 { F G R F P L L F R F }", "par": 11,
     "nudge": "One delivery is: forward, pick up, turn right, forward, place, turn round, forward, turn right, forward. Repeat it three times.",
     "intro": "Three parts, three sockets, and a shuttle run the robot could do in its sleep, if it slept."},
    {"id": "stair-haul", "name": "Stair Haul", "allow": "F L R G P S rep",
     "rows": [">p.####", "##..###", "###..##", "####..#", "#####oE"],
     "ref": "main: F G rep 4 { F R F L } P F", "par": 9,
     "nudge": "Pick up the part first. The stairs after it are the same repeating four moves as before, then place it and step onto the pad.",
     "intro": "Down the stairs again, this time with something worth carrying."},
]
