"""Chapter 2, Wind and leeway: the wind pushes a sailing ship a little to leeward of her heading. The chart prints the wind
as a range; the leeway is five percent of the wind across the ship (a stated game constant)."""

from chartkit import chart, land, reef, rock, stream, wind

CHARTS = [
    chart("wind-01", "Fresh Breeze", "wind", start=[4.0, 2.0], dest=[4.0, 18.0], deadline=5.0, naive_fails=True,
          wind=wind(270, [17, 21], 19),
          intro="A fresh breeze from the west. A sailing ship does not slide straight along her heading in a breeze: she makes some leeway, a little to leeward. Sixteen miles north, with the wind on the beam, adds up.",
          log={"arrived": "Steered upwind of the mark and let the breeze do the rest. Landed on the flag.",
               "missed": "Leeway took us east of where the log said we were. Aim a little into the wind.",
               "aground": "Pushed onto something we did not see coming.",
               "late": "Right place, wrong hour."}),
    chart("wind-02", "Lee Rocks", "wind", start=[2.0, 12.0], dest=[18.0, 12.0], deadline=5.0, naive_fails=True,
          wind=wind(0, [16, 20], 18),
          hazards=[rock("tooth-one", "First Tooth", 9.0, 10.9, 0.6), rock("tooth-two", "Second Tooth", 13.0, 10.2, 0.6)],
          intro="The wind is from the north, and the rocks lie to the south. Ships drift toward the leeward side; the rocks are on it.",
          log={"arrived": "The Teeth stayed behind us. We kept to windward and they did not bite.",
               "missed": "Clear of the Teeth, which is something. Not on the flag, which is the rest of it.",
               "aground": "The Teeth are on the lee side for a reason. They collect what the wind sends.",
               "late": "Safe and slow."}),
    chart("wind-03", "Wind and Stream", "wind", start=[3.0, 3.0], dest=[17.0, 17.0], deadline=6.0, naive_fails=True,
          wind=wind(90, [12, 16], 14), hazards=[reef("mid-reef", "Middle Reef", 10.0, 10.0, 1.0)],
          currents=[stream("diagonal-stream", "the diagonal stream", [5, 5, 19, 19], 330, [0.6, 1.0], 334, 0.8)],
          waypoints=[[3.0, 3.0], [8.0, 12.5], [17.0, 17.0]],
          intro="Two pushes at once: a stream setting north-north-west, and a wind from the east. Each is a small correction on its own. Together they are a different course.",
          log={"arrived": "Stream and wind both allowed for. The flag came up where the chart said it would.",
               "missed": "One push corrected, the other half forgotten.",
               "aground": "Middle Reef, which was in the middle.",
               "late": "We got there, in the end, by a longer way."}),
    chart("wind-04", "Lee Shore", "wind", start=[18.0, 12.0], dest=[2.0, 12.0], deadline=5.5, naive_fails=True,
          wind=wind(45, [18, 24], 21),
          land=[land("lee-island", "Lee Island", [[3, 2], [15, 2], [14, 6.5], [8, 7.5], [4, 5.5]])],
          hazards=[reef("weather-reef", "Weather Reef", 9.5, 15.5, 0.9)],
          intro="The island lies downwind of your course. A ship that forgets her leeway will be set toward a lee shore, which is the one thing a sailor does not forget twice.",
          log={"arrived": "Kept well to windward and left the island its own weather.",
               "missed": "Clear of the shore but short of the flag. The wind had opinions.",
               "aground": "Lee Island. The wind said it would happen.",
               "late": "Safe, and late, which is the right order."}),
    chart("wind-05", "The Eye", "wind", start=[11.0, 2.0], dest=[11.0, 18.0], deadline=5.0, naive_fails=True,
          wind=wind(270, [14, 18], 16),
          hazards=[reef("west-jaw", "West Jaw", 8.0, 9.5, 1.4), reef("east-jaw", "East Jaw", 14.0, 9.5, 1.4)],
          currents=[stream("the-eye-stream", "the Eye's stream", [8, 6, 14, 14], 90, [0.6, 1.0], 94, 0.8)],
          waypoints=[[11.0, 2.0], [9.8, 7.5], [11.0, 9.5], [11.5, 13.0], [11.0, 18.0]],
          intro="A gap between two reefs, with a stream and a wind that both push the same way. Wide enough to fit through, if you know where they are sending you.",
          log={"arrived": "Through the Eye and out the other side without touching either Jaw.",
               "missed": "Through the Jaws, but not onto the flag.",
               "aground": "The Eye has a narrow middle. We found its side.",
               "late": "Through, but late."}),
    chart("wind-06", "The Long Reach", "wind", size=40, start=[3.0, 3.0], dest=[37.0, 37.0], deadline=14.0, arrival_radius=2.0, naive_fails=True,
          speeds=[4.0, 8.0], wind=wind(315, [10, 14], 12),
          land=[land("great-spar", "Great Spar", [[12, 12], [26, 10], [30, 22], [22, 30], [10, 26]])],
          hazards=[reef("hobs-reef", "Hob's Reef", 35.0, 5.5, 1.3), reef("old-nick", "Old Nick", 36.0, 28.0, 1.2)],
          currents=[stream("coast-stream", "the coast stream", [28, 4, 40, 32], 0, [0.8, 1.2], 4, 1.0)],
          waypoints=[[3.0, 3.0], [28.0, 2.5], [37.5, 14.0], [31.0, 32.5], [37.0, 37.0]],
          intro="Forty miles of sea and an island in the way. A long passage, with a wind, a stream on the far side and two reefs to give the old coast its character. Plan it in legs, and take your time.",
          log={"arrived": "A long reach, well sailed. The island is behind us and so is the chapter.",
               "missed": "A long way round, and not quite the flag. Some of the error is yours; some is the sea's.",
               "aground": "The coast kept something of ours. We shall be back for it.",
               "late": "Home, but long past supper."}),
]
