"""Chapter 1, Open water: heading, speed and time; then charted hazards, a current, and finally land to go round.
Charts are content: the true values sit beside the charted ones and tests/test_charts.py keeps them honest."""

from chartkit import chart, land, reef, rock, shoal, stream

CHARTS = [
    chart("open-01", "First Light", "open", start=[3.0, 3.0], dest=[15.0, 12.0], arrival_radius=2.0, deadline=6.0,
          intro="Calm water and a clear morning. All you have is a compass, a log line and a glass: steer, count the hours, and the flag should come up ahead.",
          log={"arrived": "Landfall on the first try. The harbour master says nobody ever gets the first one wrong.",
               "missed": "We raised nothing but sea. Try the numbers again; the water was kind enough to say nothing.",
               "aground": "Aground on nothing at all, somehow. We floated off on the tide and agreed not to mention it.",
               "late": "We got there, but supper was cold."}),
    chart("open-02", "The Sisters", "open", start=[2.0, 10.0], dest=[18.0, 10.0], deadline=7.0,
          hazards=[reef("elder-reef", "Elder Reef", 8.0, 10.5, 1.3), shoal("younger-shoal", "Younger Shoal", 13.0, 9.5, 1.5)],
          waypoints=[[2.0, 10.0], [10.5, 13.5], [18.0, 10.0]], naive_fails=True,
          intro="Two old marks sit square on the direct line. The chart names them, so there is no excuse for finding them the hard way.",
          log={"arrived": "Round the Sisters and home. Elder and Younger kept their distance, as they prefer.",
               "missed": "Clear of the rocks and nowhere near the flag. Count the hours again.",
               "aground": "The Sisters keep what they catch. Gently, though; we were off by dinner.",
               "late": "We found the way round, only slowly."}),
    chart("open-03", "Gentle Set", "open", start=[2.0, 6.0], dest=[18.0, 6.0], deadline=6.0, naive_fails=True,
          currents=[stream("sound-stream", "the Sound's stream", [6, 0, 14, 20], 0, [1.3, 1.7], 3, 1.5)],
          intro="A stream runs north up the Sound. You cannot see it, but the chart says how fast it is and which way. Steering straight at the flag would carry you past it.",
          log={"arrived": "Allowed for the stream and landed on the flag. The chart told the truth, roughly.",
               "missed": "The Sound had its say. Next time, aim upstream of where you want to end.",
               "aground": "Pushed onto something we could not see. The Sound is not unkind, only unhurried.",
               "late": "On the flag, but late. The stream waits for no one."}),
    chart("open-04", "Against the Stream", "open", start=[2.0, 10.0], dest=[18.0, 10.0], deadline=5.0, naive_fails=True,
          hazards=[rock("pike-rock", "Pike Rock", 9.5, 12.6, 0.6)],
          currents=[stream("race", "the Race", [7, 0, 13, 20], 270, [1.5, 2.0], 272, 1.8)],
          intro="This one runs right at you. A stream sets west through the narrows, and the same forty minutes of sailing will not cover the same distance there.",
          log={"arrived": "Through the Race against the stream, on time. The crew want it written down that it was hard.",
               "missed": "The Race took more hours than we gave it.",
               "aground": "Pike Rock again. The chart did mention it.",
               "late": "We made it across, eventually. The Race is not a place to hurry."}),
    chart("open-05", "Bitter Head", "open", start=[2.0, 3.0], dest=[18.0, 17.0], deadline=8.0, naive_fails=True,
          land=[land("bitter-head", "Bitter Head", [[7, 8], [12, 8], [13, 12], [9, 14.5], [6, 12]])],
          hazards=[reef("little-anne", "Little Anne", 16.8, 11.0, 0.9)],
          currents=[stream("outer-stream", "the outer stream", [11, 0, 20, 14], 330, [0.8, 1.2], 335, 1.0)],
          waypoints=[[2.0, 3.0], [13.8, 6.5], [14.8, 13.5], [18.0, 17.0]],
          intro="Land at last: Bitter Head stands across the way. Going round it means turning, and a turn means a second leg and a second guess about the stream.",
          log={"arrived": "Round Bitter Head and into the lee. Two legs, two estimates, one landfall.",
               "missed": "Round the headland, and then somehow not enough of the way.",
               "aground": "Bitter Head lives up to its name. We are fine; the keel is not.",
               "late": "The long way round is long. This was longer."}),
    chart("open-06", "Two Streams", "open", start=[3.0, 10.0], dest=[17.0, 10.0], deadline=5.0, naive_fails=True,
          hazards=[rock("anvil", "The Anvil", 10.0, 10.2, 0.6), reef("long-reef", "Long Reef", 13.5, 6.0, 1.1)],
          currents=[stream("west-stream", "the west stream", [4, 0, 9, 20], 180, [2.0, 2.6], 176, 2.3),
                    stream("east-stream", "the east stream", [11, 0, 16, 20], 135, [1.0, 1.4], 138, 1.2)],
          waypoints=[[3.0, 10.0], [10.0, 12.0], [17.0, 10.0]],
          intro="A strait with a stream on each side, running opposite ways, and a rock in the calm between. By now you read a chart the way a navigator would.",
          log={"arrived": "Both streams allowed for, the Anvil passed with room to spare. Chapter done, navigator.",
               "missed": "One stream corrected, the other not. They like to be fair about it.",
               "aground": "The Anvil is where the calm is, which is exactly why it is there.",
               "late": "Through, but the second stream cost the hour."}),
]
