"""Chapter 6, Compass error: the compass does not read true. The chart prints the error as a range; the true heading of the ship is
the heading you steer PLUS the error (an east error means the compass reads low)."""

from chartkit import chart, land, reef, rock, stream, wind

CHARTS = [
    chart("comp-01", "True and Magnetic", "compass", start=[2.0, 3.0], dest=[17.0, 16.0], deadline=6.0, naive_fails=True,
          compass={"range": [6, 8], "true": 7},
          intro="Your compass is not wrong; it is just not pointing where the chart's north is. The chart prints the difference. Steer a compass heading that is already corrected for it.",
          log={"arrived": "Corrected the compass and landed on the flag. North is a matter of definition.",
               "missed": "Steered the true bearing on the compass, and the compass disagreed.",
               "aground": "Aground on nothing but arithmetic.",
               "late": "Right in the end, but late."}),
    chart("comp-02", "Iron Ship", "compass", start=[2.0, 16.0], dest=[18.0, 4.0], deadline=7.0, naive_fails=True,
          compass={"range": [-9, -7], "true": -8},
          hazards=[reef("iron-reef", "Iron Reef", 10.0, 9.5, 1.2), rock("nail-rock", "Nail Rock", 14.5, 5.5, 0.6)],
          currents=[stream("iron-stream", "the iron stream", [4, 0, 16, 14], 270, [0.6, 1.0], 274, 0.8)],
          waypoints=[[2.0, 16.0], [9.0, 13.5], [16.5, 8.5], [18.0, 4.0]],
          intro="This ship carries a good deal of iron, and her compass reads high instead: a west error. Add a stream and two marks to avoid.",
          log={"arrived": "A west error, a stream, two marks: all allowed for.",
               "missed": "Right way, wrong correction.",
               "aground": "The iron in the ship and the iron in the reef agree on very little.",
               "late": "A careful passage, a slow one."}),
    chart("comp-03", "Variation Strait", "compass", start=[2.0, 10.0], dest=[18.0, 10.0], deadline=6.0, naive_fails=True,
          compass={"range": [8, 10], "true": 9}, wind=wind(0, [14, 18], 16),
          land=[land("north-bar", "North Bar", [[7, 13], [13, 13], [12, 16], [8, 16]])],
          hazards=[reef("south-bar", "South Bar", 10.0, 6.5, 1.3)],
          waypoints=[[2.0, 10.0], [10.0, 10.5], [18.0, 10.0]],
          intro="A strait with a bar on each side and a wind from the north, and a compass nine degrees out. The gap is wide enough if every correction is right.",
          log={"arrived": "Through the strait with every correction made.",
               "missed": "Through, but off the flag.",
               "aground": "One of the bars, and a lesson in adding.",
               "late": "Through, slowly."}),
    chart("comp-04", "The Full Chart", "compass", size=30, start=[3.0, 3.0], dest=[27.0, 27.0], deadline=11.0, arrival_radius=2.0, naive_fails=True,
          speeds=[4.0, 8.0], compass={"range": [4, 8], "true": 6}, wind=wind(225, [10, 14], 12),
          land=[land("full-isle", "Full Isle", [[11, 11], [19, 12], [18, 19], [12, 18]])],
          hazards=[reef("lone-reef", "Lone Reef", 22.0, 8.0, 1.3), reef("last-reef", "Last Reef", 8.0, 23.0, 1.3)],
          currents=[stream("full-stream", "the full stream", [14, 14, 30, 30], 90, [0.8, 1.2], 94, 1.0),
                    stream("full-tide", "the high stream", [14, 0, 30, 14], 0, [1.2, 1.8], 4, 1.5, tide={"period": 12.0, "phase": 4.0})],
          waypoints=[[3.0, 3.0], [12.0, 7.0], [24.0, 14.0], [25.0, 22.0], [27.0, 27.0]],
          intro="Everything the chart can say, said at once: a compass error, a wind, a steady stream, a tidal stream, an island and two reefs. The last chart of the campaign so far.",
          log={"arrived": "Everything allowed for and the flag under the bow. The campaign so far is yours.",
               "missed": "One correction short.",
               "aground": "A reef is a reef.",
               "late": "Everything right; a little slowly."}),
]
