"""Chapter 5, Tides: a tidal stream runs one way, slackens, and runs the other. The chart prints its peak range and a timetable on
the chart's own clock (the passage starts at `start_hour`). Lie at anchor (speed 0) to wait for a fair stream."""

from chartkit import chart, land, reef, rock, stream, wind

CHARTS = [
    chart("tide-01", "Slack Water", "tides", start=[18.0, 10.0], dest=[2.0, 10.0], deadline=9.0, naive_fails=True, par_wait=4.5,
          currents=[stream("channel-tide", "the channel stream", [6, 0, 14, 20], 90, [1.6, 2.2], 90, 1.9, tide={"period": 12.0, "phase": 2.0})],
          waypoints=[[18.0, 10.0], [2.0, 10.0]],
          intro="Home lies west, and the stream through the channel runs east at first. The timetable on the chart says when it slackens and turns. A ship can lie at anchor and wait; the tide does not.",
          log={"arrived": "We waited for the turn and the sea did the rest.",
               "missed": "We left at the wrong time for the stream, or the wrong heading for the flag.",
               "aground": "Pushed onto something we could not see coming.",
               "late": "We waited too long for the fair stream."}),
    chart("tide-02", "The Narrows", "tides", start=[2.0, 10.0], dest=[18.0, 10.0], deadline=8.5, naive_fails=True, par_wait=3.0, fair_ok=False,
          hazards=[rock("narrows-rock", "Narrows Rock", 10.0, 14.0, 0.7)],
          currents=[stream("narrows-tide", "the Narrows stream", [7, 0, 13, 20], 0, [1.4, 2.0], 358, 1.7, tide={"period": 12.0, "phase": 3.0})],
          waypoints=[[2.0, 10.0], [18.0, 10.0]],
          intro="This stream crosses your course, north at its peak and south at the other. Cross at the slack and it barely moves you; cross at the peak and you must lean into it.",
          log={"arrived": "We crossed near the slack and let the Narrows barely notice.",
               "missed": "Crossed at the peak and paid for it.",
               "aground": "Narrows Rock is where the stream was taking us.",
               "late": "A long wait for a short crossing."}),
    chart("tide-03", "Two Races", "tides", start=[2.0, 10.0], dest=[18.0, 10.0], deadline=10.0, naive_fails=True, par_wait=2.5, start_hour=7.0,
          hazards=[reef("twin-reef", "Twin Reef", 10.0, 6.5, 1.0)],
          currents=[stream("first-race", "the first race", [4, 0, 9, 20], 90, [1.2, 1.8], 90, 1.5, tide={"period": 12.0, "phase": 0.0}),
                    stream("second-race", "the second race", [11, 0, 16, 20], 270, [1.2, 1.8], 270, 1.5, tide={"period": 12.0, "phase": 6.0})],
          waypoints=[[2.0, 10.0], [18.0, 10.0]],
          intro="Two tidal races a little apart, turning at different hours. The timetable is on the chart for both. It is a puzzle in timing as much as in steering.",
          log={"arrived": "Both races fair. A good deal of waiting, a good deal of sailing, well spent.",
               "missed": "One race fair, one not.",
               "aground": "Twin Reef sits between the races for a reason.",
               "late": "We caught the tides, a little behind."}),
    chart("tide-04", "Spring Tide", "tides", start=[2.0, 3.0], dest=[18.0, 17.0], deadline=10.0, naive_fails=True, par_wait=2.0, start_hour=2.0,
          wind=wind(270, [10, 14], 12),
          land=[land("tide-isle", "Tide Isle", [[8, 8], [12, 8], [12, 12], [8, 12]])],
          hazards=[reef("spring-reef", "Spring Reef", 14.0, 6.0, 1.1)],
          currents=[stream("spring-stream", "the spring stream", [0, 0, 20, 20], 45, [1.9, 2.5], 48, 2.2, tide={"period": 12.0, "phase": 4.0})],
          waypoints=[[2.0, 3.0], [11.0, 5.0], [15.0, 14.0], [18.0, 17.0]],
          intro="Spring tides run hardest. A strong stream over the whole chart, a wind, an island and a reef. Chapter five's last chart: arrive on a fair stream if you can.",
          log={"arrived": "A hard stream, ridden well. Chapter done, navigator.",
               "missed": "The stream had more to say than we did.",
               "aground": "Spring tides cover things; Spring Reef is not covered.",
               "late": "The stream was patient. We were not."}),
]
