"""Chapter 3, Fixes and landmarks: Watch-by-watch. Sail one leg, take a bearing and a distance off a landmark in sight, move
your plot to where they put you, and plan the next watch from there. A full plan up front still works; it just has no fixes."""

from chartkit import buoy, chart, headland, land, light, reef, rock, stream, wind

WATCH = {"modes": ["watch", "plan"], "default_mode": "watch"}

CHARTS = [
    chart("fix-01", "First Bearing", "fixes", start=[2.0, 2.0], dest=[18.0, 16.0], deadline=7.0, naive_fails=True, **WATCH,
          landmarks=[light("cape-light", "Cape Light", 14.0, 7.0, 9.0)],
          currents=[stream("broad-stream", "the broad stream", [0, 0, 20, 20], 70, [0.8, 1.4], 75, 1.15)],
          intro="A lighthouse stands on the cape. After a watch at sea you can take its bearing and distance, and the plot you have been keeping on paper gets corrected against it. Try the first watch.",
          log={"arrived": "A fix halfway, a corrected plot, and the flag where it should be.",
               "missed": "The fix told us how far off we were. Sooner is better.",
               "aground": "We should have taken the bearing sooner.",
               "late": "Right in the end, but the watches ran long."}),
    chart("fix-02", "Two Marks", "fixes", start=[2.0, 14.0], dest=[18.0, 4.0], deadline=7.0, naive_fails=True, **WATCH,
          landmarks=[headland("old-head", "Old Head", 8.0, 8.0, 8.0), buoy("red-buoy", "Red Buoy", 14.0, 12.0, 6.0)],
          hazards=[reef("shelf", "The Shelf", 11.0, 8.5, 1.0)],
          currents=[stream("south-set", "the south set", [4, 0, 20, 20], 200, [0.9, 1.5], 196, 1.2)],
          waypoints=[[2.0, 14.0], [10.0, 13.0], [18.0, 4.0]],
          intro="Two marks this time, a headland and a buoy. Each fix is a bearing and a distance, good to a couple of degrees and a few percent: close, not exact.",
          log={"arrived": "Two marks, two fixes, and a plot that stayed honest.",
               "missed": "Marks in sight and still short. Use them earlier.",
               "aground": "The Shelf. It is marked; the fix would have kept us clear of it.",
               "late": "Honest plot, slow passage."}),
    chart("fix-03", "Quiet Set", "fixes", start=[3.0, 3.0], dest=[17.0, 17.0], deadline=7.0, naive_fails=True, **WATCH,
          landmarks=[light("east-light", "East Light", 16.0, 5.0, 10.0), light("west-light", "West Light", 4.0, 16.0, 10.0)],
          hazards=[rock("last-rock", "Last Rock", 14.0, 16.5, 0.6)],
          currents=[stream("west-stream", "the west stream", [0, 0, 10, 20], 90, [0.8, 1.4], 94, 1.1),
                    stream("east-stream", "the east stream", [10, 0, 20, 20], 0, [0.8, 1.4], 355, 1.15)],
          intro="Two streams with two lights, one on each side. Between them a plot drifts further than you would like.",
          log={"arrived": "Two lights kept the plot honest all the way across.",
               "missed": "The lights were there; the second fix was not taken.",
               "aground": "Last Rock was last, but not last enough.",
               "late": "The sea was slower than the chart."}),
    chart("fix-04", "Beacon Run", "fixes", size=30, start=[3.0, 3.0], dest=[27.0, 27.0], deadline=10.0, arrival_radius=2.0, naive_fails=True, **WATCH,
          speeds=[4.0, 8.0], landmarks=[light("beacon", "The Beacon", 20.0, 12.0, 10.0), headland("hollow-head", "Hollow Head", 8.0, 22.0, 9.0)],
          hazards=[reef("kelp-reef", "Kelp Reef", 15.0, 15.0, 1.5), reef("shag-rock", "Shag Reef", 20.0, 23.0, 1.3)],
          wind=wind(180, [10, 14], 12),
          currents=[stream("outer-set", "the outer set", [10, 0, 30, 30], 270, [0.8, 1.4], 266, 1.1)],
          waypoints=[[3.0, 3.0], [12.0, 10.0], [21.0, 17.0], [27.0, 27.0]],
          intro="A longer run to a far headland. There is a fix to be had at the Beacon and another at Hollow Head, if you steer to see them.",
          log={"arrived": "Both marks seen, both fixes taken, and a long reach finished on the flag.",
               "missed": "A long way for a little error to grow.",
               "aground": "The reefs keep their own counsel.",
               "late": "Long watches. Short supper."}),
    chart("fix-05", "Headland Home", "fixes", start=[2.0, 15.0], dest=[18.0, 3.0], deadline=8.0, naive_fails=True, **WATCH,
          land=[land("long-point", "Long Point", [[8, 2], [14, 2], [15, 9], [11, 11], [7, 8]])],
          landmarks=[light("point-light", "Point Light", 12.0, 11.5, 9.0), headland("near-head", "Near Head", 17.0, 8.0, 8.0)],
          hazards=[reef("home-reef", "Home Reef", 15.5, 5.5, 0.9)],
          currents=[stream("point-set", "the Point set", [5, 0, 20, 14], 225, [0.9, 1.5], 229, 1.2)],
          wind=wind(315, [10, 14], 12),
          waypoints=[[2.0, 15.0], [12.0, 13.5], [18.0, 8.5], [18.0, 3.0]],
          intro="Round Long Point to a harbour behind a reef. The lights show where the point is; the reef shows where it is not worth going.",
          log={"arrived": "Round the point and home on the flag. A tidy bit of navigation.",
               "missed": "Round the point and a little wide of home.",
               "aground": "Home Reef lives up to the name, in the sense that it is by home.",
               "late": "Home, but the soup was cold."}),
]
