"""Dead Reckoning -- the par plans: the authored solution to every chart, one list of legs each.

GENERATED by tools/check_charts.py --write from each chart's `waypoints`; do not edit by hand. tests/test_charts.py
checks that every par plan still lands three stars on its chart."""

PARS = {
    "open-01": [
        {"heading": 53, "speed": 5, "hours": 3},
    ],
    "open-02": [
        {"heading": 68, "speed": 4.5, "hours": 2},
        {"heading": 114, "speed": 5.5, "hours": 1.5},
    ],
    "open-03": [
        {"heading": 101, "speed": 4, "hours": 4},
    ],
    "open-04": [
        {"heading": 90, "speed": 6, "hours": 3},
    ],
    "open-05": [
        {"heading": 76, "speed": 5, "hours": 2.5},
        {"heading": 15, "speed": 4, "hours": 1.5},
        {"heading": 46, "speed": 4.5, "hours": 1},
    ],
    "open-06": [
        {"heading": 54, "speed": 5.5, "hours": 1.5},
        {"heading": 101, "speed": 6.5, "hours": 1},
    ],
    "wind-01": [
        {"heading": 348, "speed": 4.5, "hours": 3.5},
    ],
    "wind-02": [
        {"heading": 79, "speed": 4.5, "hours": 3.5},
    ],
    "wind-03": [
        {"heading": 41, "speed": 4, "hours": 2.5},
        {"heading": 75, "speed": 5, "hours": 2},
    ],
    "wind-04": [
        {"heading": 281, "speed": 4.5, "hours": 3.5},
    ],
    "wind-05": [
        {"heading": 338, "speed": 5.5, "hours": 1},
        {"heading": 10, "speed": 4.5, "hours": 0.5},
        {"heading": 343, "speed": 3.5, "hours": 1},
        {"heading": 343, "speed": 5, "hours": 1},
    ],
    "wind-06": [
        {"heading": 86, "speed": 5, "hours": 5},
        {"heading": 38, "speed": 7, "hours": 2},
        {"heading": 333, "speed": 5.5, "hours": 3},
        {"heading": 45, "speed": 5, "hours": 1.5},
    ],
}
