"""Dead Reckoning -- the par plans: the authored solution to every chart, one list of legs each.

GENERATED by tools/check_charts.py --write from each chart's `waypoints`; do not edit by hand. tests/test_charts.py
checks that every par plan still lands three stars on its chart."""

PARS = {
    "open-01": [
        {"heading": 53, "speed": 5, "hours": 3},
    ],
    "open-02": [
        {"heading": 68, "speed": 4.5, "hours": 2},
        {"heading": 114, "speed": 5.5, "hours": 1.5},
    ],
    "open-03": [
        {"heading": 101, "speed": 4, "hours": 4},
    ],
    "open-04": [
        {"heading": 90, "speed": 6, "hours": 3},
    ],
    "open-05": [
        {"heading": 76, "speed": 5, "hours": 2.5},
        {"heading": 15, "speed": 4, "hours": 1.5},
        {"heading": 46, "speed": 4.5, "hours": 1},
    ],
    "open-06": [
        {"heading": 54, "speed": 5.5, "hours": 1.5},
        {"heading": 101, "speed": 6.5, "hours": 1},
    ],
    "wind-01": [
        {"heading": 348, "speed": 4.5, "hours": 3.5},
    ],
    "wind-02": [
        {"heading": 79, "speed": 4.5, "hours": 3.5},
    ],
    "wind-03": [
        {"heading": 41, "speed": 4, "hours": 2.5},
        {"heading": 75, "speed": 5, "hours": 2},
    ],
    "wind-04": [
        {"heading": 281, "speed": 4.5, "hours": 3.5},
    ],
    "wind-05": [
        {"heading": 338, "speed": 5.5, "hours": 1},
        {"heading": 10, "speed": 4.5, "hours": 0.5},
        {"heading": 343, "speed": 3.5, "hours": 1},
        {"heading": 343, "speed": 5, "hours": 1},
    ],
    "wind-06": [
        {"heading": 86, "speed": 5, "hours": 5},
        {"heading": 38, "speed": 7, "hours": 2},
        {"heading": 333, "speed": 5.5, "hours": 3},
        {"heading": 45, "speed": 5, "hours": 1.5},
    ],
    "fix-01": [
        {"heading": 44, "speed": 6, "hours": 3},
    ],
    "fix-02": [
        {"heading": 89, "speed": 5.5, "hours": 1.5},
        {"heading": 127, "speed": 5.5, "hours": 2},
    ],
    "fix-03": [
        {"heading": 47, "speed": 5, "hours": 3.5},
    ],
    "fix-04": [
        {"heading": 58, "speed": 6, "hours": 2},
        {"heading": 63, "speed": 6.5, "hours": 2},
        {"heading": 42, "speed": 6.5, "hours": 2},
    ],
    "fix-05": [
        {"heading": 90, "speed": 3.5, "hours": 3},
        {"heading": 104, "speed": 3.5, "hours": 2.5},
        {"heading": 174, "speed": 5, "hours": 1},
    ],
    "fog-01": [
        {"heading": 107, "speed": 5.5, "hours": 1.5},
        {"heading": 73, "speed": 5.5, "hours": 1.5},
    ],
    "fog-02": [
        {"heading": 98, "speed": 6, "hours": 1.5},
        {"heading": 32, "speed": 5.5, "hours": 1.5},
        {"heading": 33, "speed": 5, "hours": 1},
    ],
    "fog-03": [
        {"heading": 113, "speed": 6.5, "hours": 1},
        {"heading": 122, "speed": 5.5, "hours": 1.5},
        {"heading": 162, "speed": 6.5, "hours": 1.5},
    ],
    "fog-04": [
        {"heading": 85, "speed": 4, "hours": 2.5},
        {"heading": 68, "speed": 5, "hours": 1.5},
        {"heading": 5, "speed": 6.5, "hours": 1},
    ],
    "tide-01": [
        {"heading": 0, "speed": 0, "hours": 4.5},
        {"heading": 270, "speed": 4, "hours": 3.5},
    ],
    "tide-02": [
        {"heading": 0, "speed": 0, "hours": 3},
        {"heading": 94, "speed": 4, "hours": 4},
    ],
    "tide-03": [
        {"heading": 0, "speed": 0, "hours": 2.5},
        {"heading": 90, "speed": 4.5, "hours": 3},
    ],
    "tide-04": [
        {"heading": 0, "speed": 0, "hours": 2},
        {"heading": 90, "speed": 4.5, "hours": 1.5},
        {"heading": 12, "speed": 3.5, "hours": 2.5},
        {"heading": 39, "speed": 3.5, "hours": 2.5},
    ],
    "comp-01": [
        {"heading": 42, "speed": 5, "hours": 4},
    ],
    "comp-02": [
        {"heading": 117, "speed": 5, "hours": 1.5},
        {"heading": 127, "speed": 4.5, "hours": 2.5},
        {"heading": 171, "speed": 4.5, "hours": 1},
    ],
    "comp-03": [
        {"heading": 66, "speed": 4, "hours": 2},
        {"heading": 74, "speed": 4, "hours": 2},
    ],
    "comp-04": [
        {"heading": 62, "speed": 6.5, "hours": 1.5},
        {"heading": 62, "speed": 6.5, "hours": 2},
        {"heading": 353, "speed": 7.5, "hours": 1},
        {"heading": 1, "speed": 5.5, "hours": 1},
    ],
}
