"""Chapter 5, The Cold Room: spore flecks might mean a condition that spreads. A patient who might be catching goes into the cold
room bed before any scan or treatment, or the ward needs airing and the shift pays. The bed holds one patient and frees when
that patient is settled."""

from casekit import P, S

SHIFTS = [
    S("5-1", "Flecks", "A cough with green flecks on the cloth. It might be nothing, and it might be Spore Cough, which spreads. The cold room has one bed.",
      "spore soot", {"loz": 1, "roll": 1, "tonic": 1},
      [P("maren", "soot", "I swept the galley vents and now there is grey on my cloth. I was told that is soot. I would like it confirmed.")],
      tests="dye", beds=1),
    S("5-2", "Grit or Moss", "A fever with a green dusting. Moss Fever spreads in a shared ward and Grit Flush does not. Settle the bed first, then scan.",
      "moss grit", {"liners": 1, "tonic": 1, "wrap": 1},
      [P("dov", "grit", "There is grit under my skin from the weld and I am very warm. Do not tell the others I came in; I do not want them near the pipes.")],
      tests="pulse", beds=1),
    S("5-3", "One Bed, Two Patients", "Two people with flecks and one bed. Only one of them can be in the cold room at a time.",
      "spore soot moss grit", {"cells": 1, "loz": 1, "roll": 1, "tonic": 2, "wrap": 1},
      [P("kit", "soot", "Flecks on the cloth. The drones have been sweeping the vents. They are very thorough."),
       P("yusra", "moss", "A warm forehead and a green dusting. I have been in the comms booth, alone, for three days. I did not tell anyone.")],
      tests="dye lamp", beds=1),
    S("5-4", "Fleck Rash", "A rash dotted with flecks has only one name on the sheet. It spreads by touch, so it goes in the bed before anything else.",
      "fleckrash emberrash mothrash", {"roll": 1, "salve": 1, "wrap": 2},
      [P("imre", "fleckrash", "Red dots with a green edge. I have been touching everything. I wanted to be useful."),
       P("pell", "mothrash", "Pale papery patches. The cold room, I am told, is for other people.")],
      tests="dye", beds=1),
    S("5-5", "Pale Moss", "A pallor with a green dusting spreads slowly. Pale Moss has a name of its own on the sheet, so the bed matters more than the scan.",
      "palemoss hollow palew", {"salve": 1, "tonic": 1, "loz": 1},
      [P("halloran", "palemoss", "Pale. Dusted green. I did not think I could look worse than the first week and here we are."),
       P("teo", "palew", "Washed out and drowsy. I have not slept, so the drowsy is a family trait.")],
      tests="", beds=1),
    S("5-6", "Two Beds", "The second bed has been aired and made up. Two people can wait in the cold room at once.",
      "spore soot moss grit fleckrash", {"cells": 1, "loz": 1, "roll": 1, "tonic": 2, "wrap": 2},
      [P("nell", "spore", "A cough with flecks. I counted the flecks. There were four. I will not do that again."),
       P("orla", "grit", "Warm, with a dusting of something. I need to know if I can address the crew tomorrow."),
       P("maren", "fleckrash", "A rash with green dots. I took the cuttings home. I did not know.")],
      tests="dye lamp", beds=2),
    S("5-7", "Notes in the Cold Room", "Charts and flecks together: the right cure may be forbidden, and the right bed may be taken.",
      "spore soot moss grit", {"gel": 3, "roll": 2, "tonic": 2},
      [P("teo", "spore", "A cough with flecks. Nothing wick-scented, please. I have a note.", traits="wick"),
       P("kit", "moss", "A warm forehead and a dusting. I would like to be useful, so please tell me where to sit.", traits="heavy"),
       P("dov", "soot", "Flecks on the cloth. I will sit anywhere you point me. I have no opinions today.")],
      tests="dye", beds=1),
    S("5-8", "The Quiet Ward", "The last shift of the chapter. Three people, one bed, and a note on the board: the tender is nearly here.",
      "spore soot moss grit palemoss", {"gel": 2, "roll": 1, "salve": 1, "tonic": 1},
      [P("pell", "soot", "I have a cough and some grey on my cloth. I have always had grey on my cloth. It is not new."),
       P("halloran", "moss", "Fever, green dusting. I am sorry to bring it in. I only wanted to sit with someone.", traits="cold"),
       P("yusra", "palemoss", "Pale, dusted. I have been listening to the same frequency all night. It has gone very quiet.")],
      tests="dye", beds=1),
]
