"""Chapter 3, Chart Notes: a chart note forbids a kind of treatment, so the usual cure may not be the right one for this patient.
Read the note before you reach for the shelf."""

from casekit import P, S

SHIFTS = [
    S("3-1", "Read the Chart", "Dr. Aurel left notes on some of the older charts. A note on a chart is not a suggestion: the patient reacts, and the shift pays for it.",
      "coil lampeye hollow", {"gel": 1, "wrap": 1},
      [P("dov", "coil", "I do not want the cold wraps. Last time I was shaking for an hour. It is on the chart. Is it on the chart?", traits="cold")]),
    S("3-2", "Two Notes", "Two patients with two notes. A cure that is fine for one is a reaction for the other.",
      "vent coldh hollow", {"loz": 1, "gel": 1},
      [P("maren", "vent", "A cough again. The lozenges burn my tongue, so please not those.", traits="wick"),
       P("kit", "coldh", "Cold fingers. I can feel the screws less than I used to, which is a bad sign in my line of work.")]),
    S("3-3", "Heavy Hands", "Two heavy treatments never go together, and some charts forbid them outright. The shelf holds one of each kind.",
      "ember brine hollow", {"tonic": 1, "salve": 1},
      [P("orla", "ember", "A fever, not a diagnosis. I do not take heavy treatments. It is on my chart because I put it there.", traits="heavy"),
       P("pell", "brine", "Cramps and thirst. I am told the salt is up. I have always been told the salt is up.", traits="cold")]),
    S("3-4", "A Note and a Look-Alike", "Look-alike patches, and a chart note that rules out one cure for each. Decide whether to spend the roll on a scan or on a patch.",
      "emberrash mothrash", {"roll": 2, "gel": 1, "wrap": 1, "salve": 1},
      [P("imre", "emberrash", "Red patches on my neck. I put the cold salve on once and it was awful, so please not that.", traits="cold")],
      tests="dye"),
    S("3-5", "Whose Reaction", "Three patients, three notes, and a shelf too thin to give everyone the obvious thing.",
      "drift hum tide vent", {"cells": 2, "gel": 2, "loz": 2, "roll": 2, "tonic": 1, "vials": 2},
      [P("halloran", "drift", "The floor tilts. I would say I am not afraid of heights but the floor is the problem.", traits="heavy"),
       P("teo", "tide", "Slow, slow, slow. Everything tastes like stock. I am a cook; that is not a good sign.", traits="brine"),
       P("nell", "vent", "A dry cough. Please count the lozenges before giving me one. I will not be the one who used the last.", traits="wick")],
      tests="breath lamp"),
    S("3-6", "Easing Is Not Curing", "Some treatments only ease a condition: the patient is comfortable, and the shift pays a small cost. Aim to cure.",
      "coil ember brass hum", {"cells": 1, "liners": 2, "gel": 2, "tonic": 1, "salve": 1},
      [P("yusra", "brass", "The fever is in my fingertips now. I tried to tune a dial and left a thumbprint on the glass.", traits="heavy"),
       P("dov", "ember", "Warm again. I would blame the engines but they are not that warm.", traits="cold")],
      tests="lamp pulse"),
    S("3-7", "The Long Chart", "Four notes in one shift. Read each chart slowly, then the sheet, then the shelf.",
      "emberrash mothrash coldh frost seam brine", {"roll": 3, "cells": 1, "gel": 1, "tonic": 1, "drip": 2, "salve": 1},
      [P("kit", "mothrash", "Papery patches. I would put anything on them as long as it is not cold.", traits="cold"),
       P("maren", "coldh", "Cold fingers. Nothing wick-scented near the seedlings, please, and nothing near me either.", traits="wick"),
       P("pell", "seam", "A dry ache along my sides. Nothing scented with burnt wick, I have a note about it.", traits="wick")],
      tests="dye lamp"),
    S("3-8", "Dr. Aurel's Margins", "Notes in a familiar hand run down the side of the last chart. The patient is quiet and does not meet your eye.",
      "coil ember brass emberrash mothrash", {"cells": 1, "liners": 1, "roll": 3, "gel": 2, "wrap": 1, "salve": 2},
      [P("orla", "brass", "I asked Dr. Aurel not to leave. I did not ask in the right words. Never mind. Treat what is in front of you.", traits="heavy"),
       P("halloran", "emberrash", "Red patches by the wrist. I am told cold things are bad for me. I am told a great many things.", traits="cold"),
       P("teo", "mothrash", "Pale patches on the forearm. It is nothing. Everyone says that about nothing.", traits="wick")],
      tests="dye lamp pulse"),
]
