"""Chapter 2, The Second Look: look-alike conditions share their signs, so a scan has to tell them apart, and every scan uses a
supply. The plan has to work whichever way the readings come out."""

from casekit import P, S

SHIFTS = [
    S("2-1", "A Closer Look", "Two fevers that look the same. The lamp scan glows for one of them. Run it, then treat what you find.",
      "coil ember", {"cells": 1, "tonic": 1, "gel": 1},
      [P("teo", "ember", "A heat that will not break. I stood in the cold store for an hour. It did not help the soup.")],
      tests="lamp"),
    S("2-2", "Which Cough", "Three coughs, one set of signs. Two scans on the shelf, and not all of them can be wasted.",
      "vent dust rasp", {"roll": 1, "vials": 1, "loz": 1, "tonic": 1, "wrap": 1},
      [P("maren", "dust", "Grey on my handkerchief, every morning, since the filter stores were opened.")],
      tests="dye breath"),
    S("2-3", "Fever Triplet", "A fever can be one kind, the other kind, or both at once. Both scans may be needed.",
      "coil ember brass", {"cells": 1, "liners": 1, "gel": 1, "tonic": 1},
      [P("dov", "brass", "It is not a fever. It is a very warm opinion. Fix it.")],
      tests="lamp pulse"),
    S("2-4", "Two Beds", "A heavy dizziness and a smeared eye, side by side. Every scan you run is one fewer for the next person.",
      "drift hum tide lampeye static", {"roll": 1, "vials": 1, "cells": 1, "liners": 1, "gel": 1, "loz": 1, "wrap": 1, "tonic": 1},
      [P("imre", "tide", "Everything is slow, like wading through the corridor. I am nineteen, I should not be slow."),
       P("kit", "static", "My vision fizzes. Like a dead screen. I have told the drones to be gentle with me.")],
      tests="dye lamp pulse breath"),
    S("2-5", "One Cure Fits", "Sometimes two look-alikes are settled by the same treatment. Spending a scan is not the only way to be sure.",
      "coil brass lampeye static", {"liners": 1, "vials": 1, "gel": 2, "wrap": 1},
      [P("orla", "coil", "I run a hot station. I did not intend that to apply to my forehead."),
       P("pell", "lampeye", "The lamps smear again. They have always been beautiful, but this is excessive.")],
      tests="pulse breath"),
    S("2-6", "Strip or Cuff", "A paper roll is a dye strip or a patch, never both. Decide what it is for before you cut it.",
      "emberrash mothrash seam brine", {"roll": 1, "liners": 1, "wrap": 1, "salve": 1, "drip": 1, "tonic": 1},
      [P("nell", "emberrash", "Red patches on the wrist. I counted them. There are eleven."),
       P("halloran", "seam", "A tight dry ache along my sides. I did not think flying left you with anything to ache.")],
      tests="dye pulse"),
    S("2-7", "Quiet Corner", "Three people sit very still in the corner. Each one has a twin condition. Work out the cheapest honest way to tell them apart.",
      "drift hum coldh frost vent rasp", {"cells": 2, "vials": 2, "gel": 2, "loz": 1, "drip": 1, "wrap": 1},
      [P("yusra", "hum", "A low hum behind my eyes. It matches the carrier on channel nine. I would like it to stop."),
       P("teo", "frost", "Cold that goes inwards. I have started cooking for warmth, not for flavour."),
       P("maren", "rasp", "A rasp. Nothing to find, you will say. Look anyway.")],
      tests="lamp breath"),
    S("2-8", "Cold Reading", "The last shift of the month. Three patients, two scans and no spare of anything. Read slowly.",
      "coil ember emberrash mothrash coldh frost", {"roll": 1, "cells": 2, "drip": 1, "loz": 1, "salve": 1, "tonic": 1, "wrap": 2},
      [P("dov", "ember", "I hid the report because I did not want to look at it. Also, I am warm."),
       P("kit", "mothrash", "Papery patches again. The drones are not sympathetic."),
       P("halloran", "coldh", "Numb fingers. They make a clicking sound when I flex them.")],
      tests="dye lamp"),
]
