"""Chapter 6, Steady Hands: a shaking patient cannot take a scan or a treatment until they are steadied, with a steadying band
or, from the fourth shift, with Tally, the second medic robot, who can steady one patient for a whole shift."""

from casekit import P, S

SHIFTS = [
    S("6-1", "Shaking", "Some patients shake too hard to take a scan or a treatment. A steadying band holds them still first.",
      "shiver rattle", {"band": 1, "wrap": 1, "loz": 1},
      [P("imre", "shiver", "I cannot stop shaking. It is not the cold. I am not sure what it is. Please do not tell the commander.")]),
    S("6-2", "Two Bands", "Two shakers and a short shelf of bands. Everyone who shakes must be steadied before anything else.",
      "shiver rattle", {"band": 2, "gel": 1, "wrap": 1},
      [P("teo", "rattle", "A rattle in the bones. I dropped the good pan. I would like to say it was the pan."),
       P("yusra", "shiver", "My hands shake. It is the cold, I keep telling the console, and the console keeps not believing me.")]),
    S("6-3", "Twins", "Two shakes that look alike and two scans that tell them apart. Steady first, then scan, then treat.",
      "saltt loose", {"band": 1, "gel": 1, "roll": 1, "vials": 1},
      [P("pell", "loose", "My hands shake and I forget why I came in. Both are the reason. The thirst, too.")],
      tests="dye"),
    S("6-4", "Tally Arrives", "Tally, the inventory robot, has been reassigned to the infirmary. It can steady one patient per shift. It would also like you to know it counts everything.",
      "shiver rattle", {"band": 0, "wrap": 1},
      [P("dov", "shiver", "Shaking. I told Tally it was the weld. Tally said it was not the weld. I did not ask how it knew.")],
      robots=1),
    S("6-5", "One Robot, Two Shakers", "Tally can steady one patient. A band must steady the other. One band left on the shelf.",
      "shiver rattle saltt loose", {"band": 1, "gel": 1, "roll": 1, "vials": 1, "wrap": 1},
      [P("halloran", "shiver", "I am shaking. It is nothing. I have shaken on every approach for fourteen years."),
       P("kit", "saltt", "Shaking and thirsty. The drones keep bringing me water. They are very literal.")],
      tests="dye", robots=1),
    S("6-6", "The Steady Count", "Tally has counted the bands twice. It says there are not enough, politely.",
      "shiver rattle saltt loose vent", {"band": 1, "gel": 2, "roll": 1, "vials": 1},
      [P("nell", "loose", "I have counted my own tremor. Eleven a second. I do not like the number."),
       P("maren", "rattle", "A rattle in my arms. I dropped a tray of seedlings. Do not tell the seedlings."),
       P("orla", "vent", "A cough. Do not make a fuss. I did not come in for the shake, I came for the cough. I am not shaking. Why are you looking at my hands.")],
      tests="dye", robots=1),
    S("6-7", "Notes on the Shake", "A chart note, a shaking patient, and a robot that would like to help.",
      "saltt loose shiver rattle", {"band": 2, "gel": 1, "roll": 2, "vials": 1, "wrap": 1},
      [P("imre", "loose", "I am shaking and thirsty, and I cannot take the heavy ones. I have a note. I wrote it myself, so it counts.", traits="heavy"),
       P("pell", "shiver", "Shaking, and my hands are so cold. I cannot take the wick ones. The smell makes me forget.", traits="wick"),
       P("yusra", "rattle", "A rattle. I have not slept. The channel was loud tonight.")],
      tests="dye", robots=1),
    S("6-8", "The Steady Ward", "The last shift of the chapter. Four shaking, anxious, brave people, and one patient robot who has learned all their names.",
      "saltt loose shiver rattle spore soot", {"band": 1, "gel": 2, "roll": 2, "tonic": 1, "vials": 1},
      [P("kit", "rattle", "Shaking. It is nothing. It is a very large nothing."),
       P("teo", "loose", "Thirsty and shaking. I have been cooking at night again. It does not help to be at the stove with shaking hands."),
       P("dov", "soot", "I coughed on the cloth and there was green. It is soot. Tell me it is soot.", traits="wick")],
      tests="dye", robots=1, beds=1),
]
