"""Chapter 8, The Long Night: everything at once. A shaking patient, a possible spreader, a chart note and a shelf that has not
been restocked: the tender is nearly here and the infirmary has one more night to get through. The last shift closes the year."""

from casekit import P, S

SHIFTS = [
    S("8-1", "Evening Round", "The tender is two days out. Nell has counted the shelf, and then, because she is Nell, counted it again.",
      "saltt loose spore soot coil ember", {"cells": 1, "gel": 1, "roll": 1, "salve": 1, "tonic": 1, "vials": 2, "wrap": 1},
      [P("imre", "saltt", "I shake and I am thirsty. Teo says he saved me a plate. I would like to eat it sitting down."),
       P("orla", "soot", "A cough with grey flecks. I will be quick. The corridor lights need me and I need them."),
       P("nell", "coil", "A fever. I have recounted the lozenges. There is one. Please do not use it on me.")],
      tests="lamp dye breath", beds=1, robots=1),
    S("8-2", "Notes Everywhere", "Three charts, three notes, and the usual cure is wrong for every one of them. Dr. Aurel would have written this shift on the board.",
      "brass coil ember emberrash mothrash coldh frost", {"cells": 1, "drip": 1, "gel": 2, "liners": 1, "roll": 2, "salve": 1, "tonic": 1},
      [P("orla", "brass", "A fever in both hands. No heavy treatments. It is on my chart. I wrote it. I was afraid of someone else doing it.", traits="heavy"),
       P("yusra", "coldh", "Cold fingers. No wick, please. The smell reminds me of the booth.", traits="wick"),
       P("imre", "emberrash", "Red patches. Nothing cold. I am cold enough as it is.", traits="cold")],
      tests="dye lamp pulse"),
    S("8-3", "The Pair and the Shake", "One patient with two conditions, one who shakes, and a robot who has learned both names.",
      "vent brass coil rattle shiver", {"band": 1, "cells": 1, "drip": 1, "loz": 1, "vials": 1, "wrap": 2},
      [P("nell", "vent brass", "A cough and a fever, in one afternoon. I would suspect the shelf if I did not know the shelf so well."),
       P("imre", "rattle", "A rattle. I am trying to stand still. I am very good at standing still, usually."),
       P("maren", "shiver", "Shaking. It is the cold, I tell the beans. The beans are not convinced.")],
      tests="lamp", maxc=2, robots=1),
    S("8-4", "Fog on the Ring", "A green dusting on two people, and a bed for one of them. The corridor is quiet and the shelf is thin.",
      "palemoss moss grit spore soot", {"drip": 1, "gel": 1, "loz": 1, "tonic": 1, "vials": 1},
      [P("yusra", "palemoss", "Pale, with a green dusting. I have been in the booth. I will go back when you say I can."),
       P("orla", "grit", "Warm, with grit under my skin. I have a briefing and a duty and a very short patience."),
       P("dov", "soot", "Flecks on the cloth. It is soot. It was always soot. Please tell me it is soot.")],
      tests="breath", beds=1, robots=1),
    S("8-5", "The Thin Tender", "The tender is on the approach, and the shelf has never been so empty. Three patients, one chance each, and nothing to waste.",
      "saltt loose rattle shiver coldh frost", {"band": 1, "cells": 1, "drip": 1, "gel": 2, "loz": 1, "roll": 2},
      [P("imre", "loose", "Shaking, and I cannot take the heavy ones. I told Orla about my age and I still shake. I do not know what that means.", traits="heavy"),
       P("halloran", "rattle", "A rattle. I have been flying a very slow lap around the ring in my head. It helps, a bit."),
       P("pell", "coldh", "Cold fingers. I have written everyone's names on my hand and the ink has run.")],
      tests="lamp dye", robots=1),
    S("8-6", "The Long Night", "Everyone is in the infirmary, or about to be. The tender docks at dawn. Dr. Aurel's keys are on the hook. Take your time.",
      "saltt loose spore soot brass coil emberrash mothrash", {"gel": 3, "roll": 3, "tonic": 1, "vials": 2},
      [P("orla", "spore", "A cough, with flecks. I am sending everyone else home. I will stay here, in the cold room, and be a commander from the bed.", traits="wick"),
       P("imre", "loose", "I am shaking, and the shake is mostly relief. I did not expect relief to shake like this."),
       P("nell", "emberrash", "Red patches. The shelf is exactly right. I have never seen it exactly right. I am not sure what to do with my hands.", traits="cold"),
       P("yusra", "brass", "A fever, and the channel has been very quiet. I am told that is good news. I do not know how to hold good news.")],
      tests="dye breath", beds=1, robots=1),
]
