"""Chapter 4, Shared Shelves: one supply serves two jobs. The paper roll is both the dye strip and the moth patch; the glass
vials are both the breath scan and the hush draught. Every strip cut is a patch not made, so who gets scanned, and who gets
treated, is the puzzle."""

from casekit import P, S

SHIFTS = [
    S("4-1", "One Roll", "The paper roll is a dye strip or a moth patch, never both. Look at the shelf before you cut it.",
      "emberrash mothrash", {"roll": 2, "wrap": 1},
      [P("kit", "mothrash", "Red patches, or papery ones. I cannot tell. My drones have started offering opinions.")],
      tests="dye"),
    S("4-2", "The Glass Shelf", "The vials hold the breath scan and the hush draught. Nell has already counted them twice this week.",
      "static lampeye", {"gel": 1, "vials": 2},
      [P("yusra", "static", "The screens look blurred and I have started to read the static for meaning. That is a bad sign.")],
      tests="breath"),
    S("4-3", "Two on One Roll", "Two look-alikes and a single roll between them. Decide who is scanned with a strip and who gets by on a different scan.",
      "emberrash mothrash brine seam", {"drip": 1, "liners": 1, "roll": 1, "salve": 1, "tonic": 1, "wrap": 1},
      [P("nell", "emberrash", "Eleven red patches, still. I have given each of them a number."),
       P("teo", "seam", "A dry ache in the sides. I stood by the stove and it did not help.")],
      tests="dye pulse"),
    S("4-4", "Who Gets Scanned", "Three people and fewer scans than people. A treatment that fits every look-alike saves a scan.",
      "coil brass vent dust rasp hum drift", {"drip": 1, "gel": 1, "loz": 1, "roll": 2, "tonic": 1, "vials": 2, "wrap": 1},
      [P("orla", "coil", "I have a fever and a briefing in an hour. I would like to attend the briefing."),
       P("maren", "dust", "Grey dust again. The filter stores need a new door and a new person."),
       P("pell", "hum", "A hum behind the eyes. I have recorded it. It is in the key of B.")],
      tests="dye breath"),
    S("4-5", "Triage by Shelf", "There is not enough of the right thing for all three. Work out whose cure can use something else.",
      "tide drift hum vent", {"cells": 2, "gel": 2, "loz": 2, "roll": 2, "vials": 2},
      [P("dov", "tide", "I am slow today. That is a thing I used to say about other people."),
       P("halloran", "hum", "A hum. I have flown through worse. I have not flown through quieter."),
       P("imre", "vent", "A cough. I am fine. I am always fine. Please do not write fine on the chart.")],
      tests="breath lamp"),
    S("4-6", "The Thin Month", "The supply tender is late, the shelf is bare, and three people need something. Nell says she has counted, and she has.",
      "emberrash mothrash coldh frost lampeye static", {"cells": 1, "drip": 1, "gel": 1, "liners": 1, "roll": 2, "tonic": 1, "wrap": 1},
      [P("nell", "mothrash", "I have not been taking from the shelf. I want that written down. I have been taking from the back shelf."),
       P("kit", "frost", "Cold that goes inwards. My own jokes are freezing in my mouth."),
       P("yusra", "lampeye", "The lamps smear and the dials slide. I would like fewer lights in my life.")],
      tests="dye lamp pulse"),
    S("4-7", "Count Twice", "Count the roll, count the vials, count again. Four patients and every scan counts.",
      "coil ember hum tide drift brine seam", {"drip": 2, "liners": 2, "roll": 2, "salve": 3, "tonic": 1, "vials": 1, "wrap": 2},
      [P("teo", "ember", "A fever. I cooked through it. The soup is on me."),
       P("pell", "tide", "Slow and heavy. I think I have forgotten what I was going to say."),
       P("halloran", "brine", "Cramps. The salt again. I have started to hate the sea and I am a very long way from the sea."),
       P("dov", "coil", "A warm chest. I will report to you when the engines are done being hot.")],
      tests="pulse dye breath"),
    S("4-8", "Back Shelf", "Nell has opened the back shelf at last. It is smaller than anyone guessed, and no one says anything about it.",
      "emberrash mothrash static lampeye vent rasp", {"gel": 1, "liners": 1, "loz": 1, "roll": 1, "salve": 1, "vials": 1, "wrap": 2},
      [P("nell", "emberrash", "Patches on both wrists. I counted them. Then I counted the shelf. Then I stopped counting."),
       P("maren", "vent", "A cough. The seedlings are fine. I am the only one who is not."),
       P("kit", "static", "Fizzing in my sight. I am pretending it is a very bad film.")],
      tests="dye breath pulse"),
]
